parse-community/Parse-SDK-iOS-OSX

.slather.yml

Update the service for Coveralls, so it automatically is updated from Travis.

Update coveralls integration.

---

.travis.yml

Bundler caching was taking an obscene amount of time >2minutes, disable it.

Remove travis bundler caching to improve performance.

---

Parse/Internal/Installation/Constants/PFInstallationConstants.h
Parse/Internal/Installation/Constants/PFInstallationConstants.m
Parse/Internal/Installation/PFInstallationPrivate.h
Parse/PFInstallation.h
Parse/PFInstallation.m

added locale/language detection
localeIdentifier gets automatically populated whenever an installation is saved/updated

Push Translation

---

Parse-OSX.podspec
Parse.podspec
Parse/PFConstants.h
Parse/Resources/Framework.plist
Parse/Resources/FrameworkOSX.plist

Update versions for next release (1.8.1).

---

Tests/Unit/ObjectSubclassTests.m

Fix warning in tests.

---

Parse.podspec

Use the latest and greatest, as well as ultimately fixes #113 together with #115.

Update Bolts-ObjC to 1.2.1.

---

Parse/PFACL.m

There were few code branches that were not covered - this should be fixed now.
Also - reference `self` or `self class` instead of PFACL directly.

Cleanup and improve test branch coverage of PFACL.

---

Tests/Unit/UserUnitTests.m

Adding tests, nothing special.

Added tests for PFUser.signUp erroring when no username/password set.

---

Configurations/Parse-iOS.xcconfig

User other c flags, make sure that everything works great on both Xcode 6.4 and Xcode 7.0.

Update bitcode support for Xcode 7 GM.

---

Parse/Internal/LocalDataStore/SQLite/PFSQLiteDatabase.m

I guess at one point this had a purpose...

Remove unused variable in PFSQLiteDatabase

---

.travis.yml

Behold - now we have 11 builds on every Pull Request.

Added deployment and starter projects to Xcode 7 Travis.

---

Parse/Internal/User/PFUserPrivate.h
Parse/PFAnonymousUtils.m
Parse/PFUser.m

- Add new private method
- Update `PFAnonymousUtils` to use it
cc @grantland

Added private method for checking if user is linked with a given auth type.

---

Parse.podspec
Rakefile

Update Bolts to 1.2.2

---

Parse/Internal/File/State/PFFileState.h
Parse/Internal/File/State/PFFileState_Private.h
Parse/Internal/File/State/PFMutableFileState.h

Add nullability annotations to PFFileState, PFMutableFileState.

---

Parse/PFAnalytics.h

Added BFTask generics to header of PFAnalytics.

---

Parse/PFConfig.h

Added BFTask generics to header of PFConfig

---

Parse/PFAnonymousUtils.h

Added BFTask generics to header of PFAnonymousUtils

---

Parse/PFFile.h

Yo dawg I hear you like bolts.

Added BFTask generics to header of PFFile

---

Parse/Internal/Push/ChannelsController/PFPushChannelsController.m
Parse/PFObject.h

This one actually has content!

Added BFTask generics to header of PFObject

---

Parse/PFPush.h

Added BFTask generics to header of PFPush

---

Parse/PFQuery.h

Added BFTask generics to header of PFQuery

---

Parse/PFUser.h

Added BFTask generics to header of PFUser

---

Parse/PFUser.m

Make PFUser.unlinkWithAuthTypeInBackground() fully async.

---

README.md
Rakefile

Use code coverage from CodeCov only.

---

Parse/PFObject.m
Tests/Unit/ObjectUnitTests.m

Objects. Objects everywhere.
Fixes #146 (for real this time).

Fixed infinite recursion with `isDirty:` with recursive relation.

---

Parse/Internal/ACL/DefaultACLController/PFDefaultACLController.m
Parse/Internal/Commands/CommandRunner/URLSession/PFURLSessionCommandRunner.m

- PFDefaultACLController
- PFURLSessionCommandRunner

Added Bolts generics to internal implementation

---

Parse.podspec
Parse/PFConstants.h
Parse/Resources/Framework.plist
Parse/Resources/FrameworkOSX.plist

Parse 1.8.4

---

Parse/Internal/PFAlertView.m

Super simple bug, super simple fix.
Fixes #269.

Fix crash related to nil completion handler.

---

CONTRIBUTING.md

In bug reporting guidelines, link to network debugging tool.

Link to Network Debugging Tool

---

Parse/PFConstants.h
Parse/PFFile.h
Parse/PFFile.m
Tests/Unit/FileUnitTests.m

- New public API
- Updates tests
- A little bit of cleanup
cc @grantland @wangmengyan95

Added an ability to download a file and get a file path to PFFiles.

---

Parse.xcodeproj/xcshareddata/xcschemes/Parse-watchOS.xcscheme
Parse/Internal/PFDevice.m
Parse/Internal/PFInternalUtils.h
Parse/PFConstants.h

Update PFDevice for watchOS 2.

---

Parse/Internal/PFLocationManager.m

Fixed PFLocationManager on watchOS.

---

Parse.xcodeproj/project.pbxproj
Parse/Internal/PFEventuallyQueue.h
Parse/Internal/PFEventuallyQueue.m
Parse/Internal/PFEventuallyQueue_Private.h
Parse/Internal/PFReachability.h
Parse/Internal/PFReachability.m
Parse/PFConstants.h

Cleaned up reachability tracking in PFEventuallyQueue, disabled reachability for watchOS.

---

Parse/Internal/Commands/CommandRunner/URLSession/Session/TaskDelegate/PFURLSessionJSONDataTaskDelegate.m

Fix potential crash when network error doesn't have a description.

---

Parse.podspec
Parse/PFConstants.h
Parse/Resources/Framework.plist
Parse/Resources/FrameworkOSX.plist

cc @stanleyw, @wangmengyan95, @grantland who might review this piece as well.

Parse 1.9.0

---

Parse.xcworkspace/contents.xcworkspacedata
ParseStarterProject/watchOS/ParseStarterProject-Swift/ParseStarter Extension/ExtensionDelegate.swift
ParseStarterProject/watchOS/ParseStarterProject-Swift/ParseStarter Extension/Info.plist
ParseStarterProject/watchOS/ParseStarterProject-Swift/ParseStarter Extension/InterfaceController.swift
ParseStarterProject/watchOS/ParseStarterProject-Swift/ParseStarter-Swift.xcodeproj/project.pbxproj
ParseStarterProject/watchOS/ParseStarterProject-Swift/ParseStarter-Swift.xcodeproj/project.xcworkspace/contents.xcworkspacedata
ParseStarterProject/watchOS/ParseStarterProject-Swift/ParseStarter-Swift.xcodeproj/xcshareddata/xcschemes/ParseStarterProject-Swift.xcscheme
ParseStarterProject/watchOS/ParseStarterProject-Swift/ParseStarter/Assets.xcassets/AppIcon.appiconset/Contents.json
ParseStarterProject/watchOS/ParseStarterProject-Swift/ParseStarter/Base.lproj/Interface.storyboard
ParseStarterProject/watchOS/ParseStarterProject-Swift/ParseStarter/Info.plist
ParseStarterProject/watchOS/ParseStarterProject-Swift/ParseStarterProject/AppDelegate.swift
ParseStarterProject/watchOS/ParseStarterProject-Swift/ParseStarterProject/ViewController.swift
ParseStarterProject/watchOS/ParseStarterProject-Swift/Resources/Base.lproj/Main.storyboard
ParseStarterProject/watchOS/ParseStarterProject-Swift/Resources/Images.xcassets/AppIcon.appiconset/Contents.json
ParseStarterProject/watchOS/ParseStarterProject-Swift/Resources/Images.xcassets/LaunchImage.launchimage/Contents.json
ParseStarterProject/watchOS/ParseStarterProject-Swift/Resources/Info.plist

Basic starter project for watchOS 2.
Not yet deployed in any package, just adding the source code for it.

Add watchOS starter project.

---

Parse/Internal/Commands/CommandRunner/URLSession/Session/TaskDelegate/PFURLSessionFileDownloadTaskDelegate.m

Fail file downloads if the status code is not in acceptable range.

---

Parse/Internal/ACL/PFACLPrivate.h
Parse/Internal/PFEventuallyPin.h
Parse/Internal/Product/PFProduct+Private.h

Should make it tiny little bit faster to compile, maybe...

Make sure we always use angular imports for public headers.

---

Parse/Internal/Commands/CommandRunner/URLSession/Session/TaskDelegate/PFURLSessionFileDownloadTaskDelegate.m

@ghugues thanks for finding this! Tremendous help!

Fix logic for file download error handling.

---

Parse.xcworkspace/contents.xcworkspacedata
ParseStarterProject/watchOS/ParseStarterProject-Swift/ParseStarter-Swift.xcodeproj/project.pbxproj
ParseStarterProject/watchOS/ParseStarterProject-Swift/ParseStarter-Swift.xcodeproj/xcshareddata/xcschemes/ParseWatchStarter-iOS.xcscheme
ParseStarterProject/watchOS/ParseStarterProject-Swift/ParseStarter-Swift.xcodeproj/xcshareddata/xcschemes/ParseWatchStarter-watchOS.xcscheme
ParseStarterProject/watchOS/ParseStarterProject-Swift/Resources/Info.plist
Rakefile

Add watchOS project to Travis starter tests.

---

Configurations/Bolts-tvOS.xcconfig
Configurations/Parse-tvOS.xcconfig
Parse.xcodeproj/project.pbxproj
Parse.xcodeproj/xcshareddata/xcschemes/Parse-tvOS.xcscheme
Parse/Resources/Parse-tvOS.Info.plist

Add basic tvOS SDK target.

---

Configurations/Parse-tvOS.xcconfig
Parse.xcodeproj/project.pbxproj

Cleanup configuration of tvOS target.

---

Parse.xcodeproj/project.pbxproj

Remove PFPush*/PFAlertView from tvOS target.

---

Parse/Internal/PFLocationManager.m
Parse/Internal/ParseManager.h
Parse/PFAnalytics.m

Fix LocationManager, ParseManager, Analytics for tvOS.

---

Parse.xcodeproj/xcshareddata/xcschemes/Parse-tvOS.xcscheme
Parse/Internal/PFApplication.h
Parse/Internal/PFApplication.m
Parse/Internal/PFDevice.m

Fix PFDevice, PFApplication to compile for tvOS.

---

Parse/Parse.h

Disabled extensions data sharing APIs on tvOS.

---

Parse/Parse.h

Fix imports of unavailable headers for tvOS.

---

README.md

Updated README badge styles.

---

.travis.yml
Parse.podspec

Update Bolts to 1.4.0.

---

Parse/Parse.m

Fix PFProduct class not registered on tvOS.

---

Parse/Internal/Commands/PFRESTQueryCommand.m

Use proper syntax. TIL that it uses not a predicate syntax.

Fix query command construction with sorted include keys.

---

Parse/Internal/ParseManager.m
Parse/Internal/Purchase/Controller/PFPurchaseController.h
Parse/Internal/Purchase/Controller/PFPurchaseController.m
Tests/Unit/PurchaseControllerTests.m
Tests/Unit/PurchaseUnitTests.m

- Refactor all the things
- Update tests

Migrate PFPurchaseController to use dataSource for all injected controllers.

---

Parse/Internal/Object/FilePersistence/PFObjectFilePersistenceController.h
Parse/Internal/Object/FilePersistence/PFObjectFilePersistenceController.m
Tests/Unit/ObjectFilePersistenceControllerTests.m

- Use persistence groups.
- Updated tests
This actually provides waaaaay more guarantees in tests, which is a good thing.

Make PFUser, PFInstallation use persistence groups.

---

.gitignore

Store downloadable purchase content in caches folder on tvOS.

---

Parse/PFUser.h
Parse/PFUser.m

- Create a new property with a custom getter to be backward compatible
- Modernize few other parts of PFUser

Convert isAuthenticated method on PFUser to a property.

---

Parse.dev.podspec
Parse.podspec

Update Bolts to 1.5.0.

---

Parse.xcodeproj/project.pbxproj

Remove PFPush header from tvOS.

---

Parse.xcworkspace/contents.xcworkspacedata
ParseStarterProject/tvOS/ParseStarterProject-Swift/ParseStarter-Swift.xcodeproj/project.pbxproj
ParseStarterProject/tvOS/ParseStarterProject-Swift/ParseStarter-Swift.xcodeproj/project.xcworkspace/contents.xcworkspacedata
ParseStarterProject/tvOS/ParseStarterProject-Swift/ParseStarter-Swift.xcodeproj/xcshareddata/xcschemes/ParseStarter-tvOS.xcscheme
ParseStarterProject/tvOS/ParseStarterProject-Swift/ParseStarter/AppDelegate.swift
ParseStarterProject/tvOS/ParseStarterProject-Swift/ParseStarter/Base.lproj/Main.storyboard
ParseStarterProject/tvOS/ParseStarterProject-Swift/ParseStarter/Info.plist
ParseStarterProject/tvOS/ParseStarterProject-Swift/ParseStarter/ViewController.swift
Rakefile

Add tvOS starter project.

---

Parse/Internal/ACL/State/PFACLState.h
Parse/Internal/ACL/State/PFACLState.m
Parse/Internal/Object/Coder/File/PFObjectFileCodingLogic.m
Parse/Internal/Object/State/PFObjectState.h
Parse/Internal/Object/State/PFObjectState.m
Parse/Internal/User/Coder/File/PFUserFileCodingLogic.m
Parse/Internal/User/State/PFUserState.h
Parse/Internal/User/State/PFUserState.m
Parse/PFObject.m
Parse/PFUser.m

Update state mutation of PFObject/PFUser to use mutating blocks.

---

Parse/Internal/PFEncoder.m

Use `weak` instead of `assign`.
Also improved constructor by not going through every property setter and assigning default values directly.

Fix potential crash in PFOfflineObjectEncoder.

---

Parse/Internal/Commands/PFRESTPushCommand.m
Parse/Internal/Push/State/PFMutablePushState.h
Parse/Internal/Push/State/PFMutablePushState.m
Parse/Internal/Push/State/PFPushState.h
Parse/Internal/Push/State/PFPushState.m
Parse/Internal/Push/State/PFPushState_Private.h
Parse/PFPush.h
Parse/PFPush.m
Tests/Unit/PushCommandTests.m
Tests/Unit/PushStateTests.m

Matching functionality for https://github.com/ParsePlatform/Parse-SDK-dotNET/pull/94
Also added tests to validate all the new logic.
cc @stanleyw @grantland

Add ability to specify scheduled delivery time when sending push notifications.

---

Parse/PFObject.m

We were not removing the object itself when saving children, which simply task-deadlocked, as the save is already in progress for the root object.
This is following the same code as we have for `saveEventually`, where we explicitly remove root object from the list of unique objects to save, unless we were given an array.
Collection of dirty children will expand any `PFObject` into dictionary representation of it's estimatedData, so it's absolutely save to just pass a parse object as the root here.
Concrete example of the issue:
```
- obj2.save()
- obj2[key1] = obj1
- obj2.save()
---
- obj2[key2] = "randomValue"
- obj2.save() // It used to hang here...
```
Fixes #587.

Fix deadlock on saving an object with a circular reference.

---

Parse.podspec
Parse/PFConstants.h
Parse/Resources/Parse-OSX.Info.plist
Parse/Resources/Parse-iOS.Info.plist
Parse/Resources/Parse-tvOS.Info.plist
Parse/Resources/Parse-watchOS.Info.plist
ParseStarterProject/OSX/ParseOSXStarterProject-Swift/Resources/Info.plist
ParseStarterProject/OSX/ParseOSXStarterProject/Resources/Info.plist
ParseStarterProject/iOS/ParseStarterProject-Swift/Resources/Info.plist
ParseStarterProject/iOS/ParseStarterProject/Resources/Info.plist
ParseStarterProject/tvOS/ParseStarterProject-Swift/ParseStarter/Info.plist
ParseStarterProject/watchOS/ParseStarterProject-Swift/ParseStarter Extension/Info.plist
ParseStarterProject/watchOS/ParseStarterProject-Swift/ParseStarter/Info.plist
ParseStarterProject/watchOS/ParseStarterProject-Swift/Resources/Info.plist

Parse 1.11.0 :tv: :watch:

---

Parse/Internal/BFTask+Private.h
Parse/Internal/BFTask+Private.m
Parse/Internal/User/AuthenticationProviders/Controller/PFUserAuthenticationController.h
Parse/Internal/User/AuthenticationProviders/Controller/PFUserAuthenticationController.m

Don't get global via `PFUser.+userController`, but inject it via `dataSource`.

Inject user controller into UserAuthenticationController.

---

Parse/Internal/Commands/PFRESTObjectBatchCommand.h
Parse/Internal/Commands/PFRESTObjectBatchCommand.m
Parse/Internal/Object/BatchController/PFObjectBatchController.m
Parse/PFObject.m
Tests/Unit/ObjectBatchCommandTests.m
Tests/Unit/ObjectBatchControllerTests.m

Generate path from the injected server URL for batch command.

---

Parse/Internal/User/AuthenticationProviders/Controller/PFUserAuthenticationController.m

Also slightly improves performance, as we are no longer creating a lazy anonymous user if it doesn't exist.
This has no impact on the end API behaviour.
Depends on #675.

Make UserAuthenticationController.logInUserAsync fully async.

---

Parse.podspec

Update podspecs to include deprecated categories.

---

Parse/Internal/LocalDataStore/OfflineStore/PFOfflineStore.h
Parse/Internal/LocalDataStore/OfflineStore/PFOfflineStore.m

This adds generic types to object collections and tasks in PFOfflineStore.

Add generic types to PFOfflineStore.

---

.gitmodules
Cartfile
Cartfile.resolved
Configurations/Parse-OSX.xcconfig
Configurations/Parse-iOS.xcconfig
Configurations/Parse-tvOS.xcconfig
Configurations/Parse-watchOS.xcconfig
Configurations/ParseUnitTests-OSX.xcconfig
Configurations/ParseUnitTests-iOS.xcconfig
Parse.xcodeproj/project.pbxproj
ParseStarterProject/OSX/ParseOSXStarterProject-Swift/ParseOSXStarterProject-Swift.xcodeproj/project.pbxproj
ParseStarterProject/OSX/ParseOSXStarterProject/ParseOSXStarterProject.xcodeproj/project.pbxproj
ParseStarterProject/iOS/ParseStarterProject-Swift/ParseStarterProject-Swift.xcodeproj/project.pbxproj
ParseStarterProject/iOS/ParseStarterProject/ParseStarterProject.xcodeproj/project.pbxproj
ParseStarterProject/tvOS/ParseStarterProject-Swift/ParseStarter-Swift.xcodeproj/project.pbxproj
ParseStarterProject/watchOS/ParseStarterProject-Swift/ParseStarter-Swift.xcodeproj/project.pbxproj

This PR moves the submodule reference to the new location under `Carthage/Checkouts/Bolts-iOS` and updates all internal references to use that location.
Contributes to #8

Use Bolts via Carthage.

---

Parse/Internal/File/Controller/PFFileController.m

Fix expensive cached file path getter in FileController.

---

Gemfile.lock

- `bundle update`
- `git commit -m "Update all the gems"`
- `git push`
- `hub pr -o`
- ???
- Profit

Update all the gems.

---

Parse/Internal/Commands/CommandRunner/URLRequestConstructor/PFCommandURLRequestConstructor.m
Parse/Internal/PFInternalUtils.h
Parse/Internal/PFInternalUtils.m

Use NSURL APIs, fail on error.

Improve content-length calculation for file upload requests.

---

Parse/Internal/Commands/CommandRunner/URLSession/Session/TaskDelegate/PFURLSessionUploadTaskDelegate.m
Parse/Internal/LocalDataStore/OfflineStore/PFOfflineStore.m
Parse/Internal/LocalDataStore/SQLite/PFSQLiteDatabase.h
Parse/Internal/Persistence/PFPersistenceController.h
Parse/PFConfig.h
Parse/PFConstants.h
Parse/PFGeoPoint.h
Parse/PFPurchase.h
Parse/PFQuery.h
Parse/PFSession.h
Parse/PFUser.h
Tests/Unit/PushUnitTests.m

Since we require Xcode 7 - we can use this syntax now for everything.

Update nullability specifier syntax to latest.

---

Parse/Internal/File/Controller/PFFileController.h
Parse/Internal/File/Controller/PFFileController.m
Tests/Unit/FileControllerTests.m

- Add validation to prevent future regression.
- Add generic types to all methods of PFFileController.

Fixed not set url for new file uploads.

---

Parse/Internal/ParseManager.m

Sort of contributes to the whole thing with boolean logic.
Thank you @coolioxlr for catching this.

Fixed PurchaseController not initialized on tvOS.

---

Parse.xcodeproj/project.pbxproj
Parse.xcodeproj/xcshareddata/xcschemes/Parse-OSX.xcscheme
Parse.xcodeproj/xcshareddata/xcschemes/Parse-iOS-Dynamic.xcscheme
Parse.xcodeproj/xcshareddata/xcschemes/Parse-iOS.xcscheme
Parse.xcodeproj/xcshareddata/xcschemes/Parse-tvOS-Dynamic.xcscheme
Parse.xcodeproj/xcshareddata/xcschemes/Parse-tvOS.xcscheme
Parse.xcodeproj/xcshareddata/xcschemes/Parse-watchOS-Dynamic.xcscheme
Parse.xcodeproj/xcshareddata/xcschemes/Parse-watchOS.xcscheme
ParseStarterProject/OSX/ParseOSXStarterProject-Swift/ParseOSXStarterProject-Swift.xcodeproj/project.pbxproj
ParseStarterProject/OSX/ParseOSXStarterProject-Swift/ParseOSXStarterProject-Swift.xcodeproj/xcshareddata/xcschemes/ParseOSXStarterProject-Swift.xcscheme
ParseStarterProject/OSX/ParseOSXStarterProject-Swift/Resources/Info.plist
ParseStarterProject/OSX/ParseOSXStarterProject/ParseOSXStarterProject.xcodeproj/project.pbxproj
ParseStarterProject/OSX/ParseOSXStarterProject/ParseOSXStarterProject.xcodeproj/xcshareddata/xcschemes/ParseOSXStarterProject.xcscheme
ParseStarterProject/OSX/ParseOSXStarterProject/Resources/Info.plist
ParseStarterProject/iOS/ParseStarterProject-Swift/ParseStarterProject-Swift.xcodeproj/project.pbxproj
ParseStarterProject/iOS/ParseStarterProject-Swift/ParseStarterProject-Swift.xcodeproj/xcshareddata/xcschemes/ParseStarterProject-Swift.xcscheme
ParseStarterProject/iOS/ParseStarterProject-Swift/Resources/Info.plist
ParseStarterProject/iOS/ParseStarterProject/ParseStarterProject.xcodeproj/xcshareddata/xcschemes/ParseStarterProject.xcscheme
ParseStarterProject/tvOS/ParseStarterProject-Swift/ParseStarter-Swift.xcodeproj/xcshareddata/xcschemes/ParseStarter-tvOS.xcscheme
ParseStarterProject/watchOS/ParseStarterProject-Swift/ParseStarter-Swift.xcodeproj/xcshareddata/xcschemes/ParseWatchStarter-iOS.xcscheme
ParseStarterProject/watchOS/ParseStarterProject-Swift/ParseStarter-Swift.xcodeproj/xcshareddata/xcschemes/ParseWatchStarter-watchOS.xcscheme

- Update all the things
- Re-run "Validate Settings" on every project
- Also adopted usage of few new settings in starter projects
- No changes in any of the framework targets.

Update all projects, schemes for Xcode 7.3.

---

Parse/PFFile.m
Tests/Unit/FileUnitTests.m

Closes #820 
If Travis-CI is going to fail - it's due to Carthage update vs install which is pending inside #828

Remove client-side PFFile size limitation.

---

.gitmodules
Cartfile
Cartfile.resolved
Parse.xcodeproj/project.pbxproj
Parse.xcworkspace/contents.xcworkspacedata
ParseStarterProject/OSX/ParseOSXStarterProject-Swift/ParseOSXStarterProject-Swift.xcodeproj/project.pbxproj
ParseStarterProject/OSX/ParseOSXStarterProject/ParseOSXStarterProject.xcodeproj/project.pbxproj
ParseStarterProject/iOS/ParseStarterProject-Swift/ParseStarterProject-Swift.xcodeproj/project.pbxproj
ParseStarterProject/iOS/ParseStarterProject/ParseStarterProject.xcodeproj/project.pbxproj
ParseStarterProject/tvOS/ParseStarterProject-Swift/ParseStarter-Swift.xcodeproj/project.pbxproj
ParseStarterProject/watchOS/ParseStarterProject-Swift/ParseStarter-Swift.xcodeproj/project.pbxproj
README.md
Rakefile

It's no longer Bolts-iOS, but it's Bolts-ObjC.

Update Bolts submodule link and path.

---

Parse/Internal/Installation/CurrentInstallationController/PFCurrentInstallationController.m

Make it fully async, since waiting there is not helpful.
Fixes #817.

Make loading of installationIdentifier from disk fully async.

---

Tests/Other/Swift/SwiftSubclass.swift

- Properly attach colons
- Remove trailing semicolons

Cleanup swift test helper.

---

Cartfile.resolved
Parse.podspec

Bolts -> 1.7
xctoolchain -> latest master.

Update Bolts, xctoolchain to latest.

---

Parse/Internal/ParseManager.m
Parse/PFConfig.h
Parse/PFConfig.m
Parse/PFInstallation.h
Parse/PFInstallation.m
Parse/PFUser.h
Parse/PFUser.m

This is a long-time-ago requested and very useful API.

Add APIs to load current user, installation, config asynchronously.

---

.codecov.yml

Disables annoying comments and required patch status checks.

Add CodeCov configuration.

---

Parse.podspec
Parse/PFConstants.h
Parse/Resources/Parse-OSX.Info.plist
Parse/Resources/Parse-iOS.Info.plist
Parse/Resources/Parse-tvOS.Info.plist
Parse/Resources/Parse-watchOS.Info.plist
ParseStarterProject/OSX/ParseOSXStarterProject-Swift/Resources/Info.plist
ParseStarterProject/OSX/ParseOSXStarterProject/Resources/Info.plist
ParseStarterProject/iOS/ParseStarterProject-Swift/Resources/Info.plist
ParseStarterProject/iOS/ParseStarterProject/Resources/Info.plist
ParseStarterProject/tvOS/ParseStarterProject-Swift/ParseStarter/Info.plist
ParseStarterProject/watchOS/ParseStarterProject-Swift/ParseStarter Extension/Info.plist
ParseStarterProject/watchOS/ParseStarterProject-Swift/ParseStarter/Info.plist
ParseStarterProject/watchOS/ParseStarterProject-Swift/Resources/Info.plist

Parse 1.14.0 ☁️

---

Parse/Internal/Object/Subclassing/PFObjectSubclassingController.m

Fixed crash when an NSBundle without executable is loaded

---

Parse/PFConstants.h

Updated version from @"1.14.2" to @"1.14.3"

Updated Parse Version No @"1.14.3"

---

Parse/Internal/PFReachability.m

fixes issue affecting list of listeners

---

Parse.podspec

Change FacebookUtils deployment target from 9.0 to 8.0

---

.gitmodules
Parse/Parse/Internal/Commands/PFRESTQueryCommand.m
Parse/Parse/Internal/KeyValueCache/PFKeyValueCache.h
Parse/Parse/Internal/Object/PFObjectPrivate.h
Parse/Parse/Internal/Object/State/PFObjectState.m
Parse/Parse/Internal/Object/Utilities/PFObjectUtilities.h
Parse/Parse/Internal/PFAssert.h
Parse/Parse/Internal/Query/Controller/PFQueryController.h
Parse/Parse/PFEncoder.m
Parse/Parse/PFObject.m

- Fixes analyzer issue
- Fixes #1240

Fixes analyzer flags, fix release builds

---

Parse/Parse/Internal/Analytics/Controller/PFAnalyticsController.m

Fix an issue preventing events without dimensions to be send

---

Parse/Parse/Internal/PFKeychainStore.m

Fixes #1352
Because `_dataForKey` now does a conversion of the keychain item, it is no longer safe to call it concurrently. This means that all uses of `_synchronizationQueue` need to be serial, so converting it to a serial queue and removing the barrier calls works better.

Fix race condition related to keychain conversion

---

Parse/Parse/PFObject.m
Parse/Tests/Unit/ObjectUnitTests.m
Parse/Tests/Unit/PolygonUnitTests.m

Closes https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1361

Fix issue saving Polygon to Object

---

CHANGELOG.md
Parse.podspec
ParseFacebookUtils/ParseFacebookUtils/Internal/AuthenticationProvider/tvOS/PFFacebookDeviceAuthenticationProvider.m
ParseTwitterUtils/ParseTwitterUtils/PFTwitterUtils.m
ParseTwitterUtils/Tests/Unit/TwitterUtilsTests.m

Just some final tweaks before we release

1.17.3 release tweaks

---

CHANGELOG.md

Fixes Changelog

---

CONTRIBUTING.md
README.md

- Move info about releases to contributing doc
- Remove license info from README

Readme and contributing doc improvements

---

CHANGELOG.md
Parse.podspec
Parse/Parse/PFConstants.h
Parse/Parse/Resources/Parse-OSX.Info.plist
Parse/Parse/Resources/Parse-iOS.Info.plist
Parse/Parse/Resources/Parse-tvOS.Info.plist
Parse/Parse/Resources/Parse-watchOS.Info.plist
ParseFacebookUtils/Resources/Info-iOS.plist
ParseFacebookUtils/Resources/Info-tvOS.plist
ParseStarterProject/OSX/ParseOSXStarterProject-Swift/Resources/Info.plist
ParseStarterProject/OSX/ParseOSXStarterProject/Resources/Info.plist
ParseStarterProject/iOS/ParseStarterProject-Swift/Resources/Info.plist
ParseStarterProject/iOS/ParseStarterProject/Resources/Info.plist
ParseStarterProject/tvOS/ParseStarterProject-Swift/ParseStarter/Info.plist
ParseStarterProject/watchOS/ParseStarterProject-Swift/ParseStarter Extension/Info.plist
ParseStarterProject/watchOS/ParseStarterProject-Swift/ParseStarter/Info.plist
ParseStarterProject/watchOS/ParseStarterProject-Swift/Resources/Info.plist
ParseTwitterUtils/Resources/Info.plist
ParseUI/Resources/Info.plist

By popular demand, updates the Facebook SDK to 9.x.
Close #1608

Release 1.19.2

---

README.md

Fix release badge in README

---

.circleci/config.yml

Related issue: #1656 
Increase timeout.
n/a

ci: fix CircleCI carthage timeout

---

README.md

Platform badge in readme not rendered.
Related issue: #n/a
Fix platform badge in readme.
n/a

docs: fix platform badge in readme

---

.github/workflows/release-automated.yml

Release workflow failed because of incorrect ruby version.
Closes: #n/a
Added ruby setup to workflow,.
n/a

ci: Fix release workflow ruby version

---

.github/workflows/ci.yml
Package.swift

Closes: #1694 
Add Bolts dependency as fork in org.
n/a

fix: Adding via SPM doesn't work due to unstable Bolts dependency

---

CONTRIBUTING.md

Remove code style reference from CONTRIBUTING guide. 
Closes: #n/a

docs: Remove code style reference from CONTRIBUTING

---

Parse/Parse.xcodeproj/xcshareddata/xcschemes/Parse-macOS.xcscheme
Parse/Tests/Other/TestCases/UnitTestCase/PFUnitTestCase.m

Looks like this was manually added to the scheme instead of going through XCode UI. Hopefully this will reduce the amount of flaky tests.
Closes: https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1677

ci: Fix failing macOS tests

---

Package.resolved
Package.swift
Parse.xcworkspace/xcshareddata/swiftpm/Package.resolved
Parse/Parse.xcodeproj/project.pbxproj
ParseLiveQuery/ParseLiveQuery.xcodeproj/project.pbxproj

We need to update the version of Starscream to support Privacy Manifest requirements.
https://github.com/daltoniam/Starscream/compare/4.0.6...4.0.8
ref: https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1785

refactor: Update Starscream to 4.0.8

---

README.md

Closes: n/a
Add chat badge to README.

docs: Add chat badge to README

---

.github/dependabot.yml
.github/workflows/ci.yml
Rakefile

Fixes 2 CI issues:
- Incorrect dependabot PR title
- Codecov not running

ci: Fix codecov and dependabot default commit prefix
