parse-community/Parse-SDK-iOS-OSX

Tests/Other/TestCases/TestCase/PFTestCase.h, Tests/Other/TestCases/TestCase/PFTestCase.m
Convert the rest of defines to use XCTAssert, remove the old GHUnit-based ones as they are unused.
=> Remove old GHUnit defines.

Parse/Internal/Object/Subclassing/PFObjectSubclassingController.m
Fixes #13. This was broken due to `NSJSONSerialization` serializing all `NSNumbers` as '0' and '1', but any `CFBoolean`s as `true` and `false`. We now re-add explicit support for booleans.
=> Re-add proper boolean support for object subclassing.

Parse/PFPush.m, Tests/Unit/PushMobileTests.m
Previously there was a crash when receiving a push notification which had its sound set to `null`. This resulted in `soundName` being `NSNull` and crashed when checking for its length.
=> Fix a crash when receiving a push notification with null sound

README.md
=> Fixed compiling instructions in README.

Parse/Internal/Query/Controller/PFCachedQueryController.m, Parse/PFGeoPoint.m, Parse/PFObject.m, Parse/PFRole.h, Parse/PFRole.m
Improved many places where we do weird assertions, or where we use a condition but could have used a macro. Also fixed some typos.
Improves the bigger enhancement request in #6
=> Cleanup assertions, convert to macros where possible.

Parse/PFObject.m, Tests/Unit/ObjectSubclassTests.m
**This is only a temporary workaround**. We should go back and clean up, not only our uses of the '_pfinternal_state' ivar directly, but also discuss whether our auto property synthesis still makes sense to have as a feature.
This prevents conflicts with our automatic property synthesis that is done for registered subclasses.
=> Rename PFObject '_state' instance variable to '_pfinternal_state'.

Parse/Internal/Commands/CommandRunner/URLSession/Session/TaskDelegate/PFURLSessionFileDownloadTaskDelegate.m, Parse/Internal/Commands/CommandRunner/URLSession/Session/TaskDelegate/PFURLSessionJSONDataTaskDelegate.m, Tests/Unit/URLSessionDataTaskDelegateTests.m, Tests/Unit/URLSessionTests.m, Tests/Unit/URLSessionUploadTaskDelegateTests.m
Still store in `originalError`, but add it to `NSUnderlyingErrorKey` as well.
=> Store original network error under NSUnderlyingError key.

Tests/Unit/InstallationUnitTests.m, Tests/Unit/ObjectSubclassTests.m, Tests/Unit/ObjectUnitTests.m, Tests/Unit/ParseModuleUnitTests.m, Tests/Unit/UserUnitTests.m
Most of these have low signal, compared to simply looking at the log from the assertion or re-running the test, so remove them.
InstallationUnitTests ones had wrong descriptions there.
=> Cleanup test assertions descriptions.

Parse-OSX.podspec, Parse.podspec
=> Deprecate Parse-OSX pod, add OS X support to Parse pod.

Parse.xcodeproj/project.pbxproj
Apparently we didn't remove this from phases, but we are not using only libOCMock.a right now to not break Xcode 7.
=> Remove unused OCMock.framework from copy frameworks stage of ParseUnitTests-iOS.

Parse/PFAnalytics.h, Parse/PFAnonymousUtils.h, Parse/PFCloud.h, Parse/PFConfig.h, Parse/PFFile.h, Parse/PFObject.h, Parse/PFProduct.h, Parse/PFPush.h, Parse/PFQuery.h, Parse/PFSession.h, Parse/PFUser.h, ParseStarterProject/OSX/ParseOSXStarterProject-Swift/ParseOSXStarterProject/AppDelegate.swift, ParseStarterProject/iOS/ParseStarterProject-Swift/ParseStarterProject/AppDelegate.swift
This is needed to eliminate the need for explicit import of Bolts in Swift projects.
As soon as we import BFTask in our headers - all the APIs that return a BFTask magically become visible to Swift projects without the need for importing Bolts.
=> Explicitly import Bolts/BFTask to eliminate the need for explicit Bolts import in Swift projects.

Parse.xcodeproj/project.pbxproj, Parse/Internal/File/Controller/PFFileController.h, Parse/Internal/File/Controller/PFFileController.m, Parse/Internal/File/Controller/PFFileStagingController.h, Parse/Internal/File/Controller/PFFileStagingController.m, Parse/PFFile.m, Tests/Unit/FileControllerTests.m, Tests/Unit/FileUnitTests.m
Previously, our file staging code was not centralized, wasn't very efficient, and most importantly made testing & migration difficult.
Fixes half of #18.
=> Added PFFileStagingController to manage staging.

Parse/PFPurchase.h, Parse/PFPush.h, Tests/Unit/PurchaseUnitTests.m
These were still missing - add them.
=> Add nullability annotations to 100% of public API.

Parse/Internal/PFGeoPointPrivate.h, Parse/PFGeoPoint.h, Parse/PFGeoPoint.m
Use `instancetype` instead of returning PFGeoPoint.
=> Add better subclassing support to PFGeoPoint.

Parse/Internal/PFAlertView.m, Tests/Unit/AlertViewTests.m
This logic doesn't handle 32/64 bit conversions, so just hard-code it to use style and cancelButtonIndex.
It's goping to be waaay safer this way.
=> Fixed PFAlertView cancel button handling logic.

Parse/Internal/PFAlertView.m, Tests/Unit/AlertViewTests.m
Fixes #71
Whenever a rootViewController has presented view controller - we fail to acknowledge it and present our UIAlertController on the wrong view controller, which usually leads to no presentation at all.
=> Fixed presentation of PFAlertView when rootViewController has presentedViewController.

Parse/Internal/PropertyInfo/PFPropertyInfo.m
We now walk the class heirarchy for the synthesized variable. This may help in nested subclass use cases with a different synthesized name.
=> Added weak/assign value support for PFPropertyInfo, and improved @synthesize detection.

Parse/Internal/Commands/CommandRunner/PFCommandRunningConstants.h, Parse/Internal/Commands/CommandRunner/PFCommandRunningConstants.m, Parse/Internal/Commands/CommandRunner/URLSession/PFURLSessionCommandRunner.m, Parse/Internal/Commands/CommandRunner/URLSession/PFURLSessionCommandRunner_Private.h, Parse/Internal/Commands/CommandRunner/URLSession/Session/PFURLSession.h, Parse/Internal/Commands/CommandRunner/URLSession/Session/PFURLSession.m, Parse/Internal/Commands/CommandRunner/URLSession/Session/PFURLSession_Private.h, Parse/Internal/Commands/CommandRunner/URLSession/Session/TaskDelegate/PFURLSessionDataTaskDelegate.h, Parse/Internal/Commands/CommandRunner/URLSession/Session/TaskDelegate/PFURLSessionDataTaskDelegate_Private.h, Tests/Unit/URLSessionCommandRunnerTests.m, Tests/Unit/URLSessionTests.m
This is required #74
- Added delegate to PFURLSession
- Updated Tests
- Added NSNotification posting whenever the request will be sent/finished.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/parseplatform/parse-sdk-ios-osx/82)
=> Added NSNotifications being posted on every network request being sent/finished.

Parse/PFNetworkActivityIndicatorManager.m
Fixes #74 
Depends on #82 
Just subscribe it to the network indicator.
=> Add automatic management of Network Activity Indicator on iOS.

Parse/Internal/ParseManager.m, Parse/Internal/Purchase/Controller/PFPurchaseController.h, Parse/Internal/Purchase/Controller/PFPurchaseController.m, Tests/Unit/PurchaseControllerTests.m, Tests/Unit/PurchaseUnitTests.m
Start using `appStoreReceiptURL` instead of transaction receipts, that are deprecated in iOS 9.
=> Implemented In-App-Purchase validation using App Store Receipt instead of Transaction Receipt.

Parse/Internal/PropertyInfo/PFPropertyInfo.m
We get into in infinite recursion if there are 2 subclasses of PFObject and the property is implemented on the superclass doesn't have an instance variable.
This fixes the problem. Looks like a typo in the first place.
@richardjrossiii Would be awesome to have tests on this.
=> Fix potential infinite recursion on resolving PFObject subclass properties.

Parse/Resources/FrameworkOSX.plist
This will cause the code signature to fail, since apparently it looks for executable first, then for entire folder.
Fixes #98
=> Properly specify bundle executable in OS X framework Info.plist.

Parse/PFObject.m
If there are no other references to `self` (aka PFObject instance) - evicting this object too early here will actually cause the object
to be gone from memory and then inside the last continuation - it will be `nil`.
This is reproducible by calling `delete/fetchInBackground` on an instance of PFObject and never referencing that instance again.
Fixes #100
=> Fixed too agressive deallocation for PFObject when fetch/delete is in  progress.

Parse/Internal/Commands/PFRESTCommand.m, Parse/Internal/Commands/PFRESTQueryCommand.m, Parse/Internal/FieldOperation/PFFieldOperation.m, Parse/Internal/LocalDataStore/OfflineQueryLogic/PFOfflineQueryLogic.m, Parse/Internal/LocalDataStore/OfflineStore/PFOfflineStore.m, Parse/Internal/Object/LocalIdStore/PFObjectLocalIdStore.m, Parse/Internal/PFJSONSerialization.m, Parse/Internal/Query/Utilities/PFQueryUtilities.m, Parse/PFUser.m
We no longer do `@throw [NSException exceptionWith...]` anywhere in the code base, replaced usages of `if (conditon) [NSException raise:...` with PFParamter/ConsistencyAssert where appropriate.
This is related to #6.
=> Cleaned up usages of exceptions and asserts.

Parse/Internal/FieldOperation/PFFieldOperation.m
=> Fixed assertion messages that were unintentionally changed in #86.

Parse/Internal/Object/OperationSet/PFOperationSet.h, Parse/Internal/Object/OperationSet/PFOperationSet.m, Tests/Unit/OperationSetUnitTests.m
- Add `removeAllObjects` to `PFOperationSet`.
- Add a test for it.
Should help to implement #52, specifically #70
=> Add ability to remove all field operations from PFOperationSet.

Parse/Internal/PFAlertView.h, Parse/Internal/PFApplication.h, Parse/Internal/PFApplication.m, Parse/Internal/PFLocationManager.m, Parse/Internal/Push/PFPushPrivate.h, Parse/PFNetworkActivityIndicatorManager.m, Parse/PFPush.h
- Mark extension unavailable APIs
- Add workaround for UIApplication/NSApplication sharedApplication (it will be nil anyway)
Tested that it compiles for extensions by enabling `allow extension only APIs on both targets`.
We probably should have a sample application with a sample extension inside, so we can test this on a CI.
Fixes #43 though, since we fully compile for app extensions now.
=> Make sure we compile for App Extensions from source.

Parse/PFObject.m, Tests/Unit/ObjectUnitTests.m
Return an error, avoid throwing, add test.
Contributes to #6.
cc @grantland
=> Replace exception with error on PFObject.fetch without an objectId.

Parse.xcodeproj/project.pbxproj, Scripts/build_third_party.sh, Scripts/xctask/build_framework_task.rb
=> Fixed build scripts not working when contained in path with spaces.

Parse/PFObject.h, Parse/PFObject.m, Tests/Unit/ObjectUnitTests.m
=> Ability to revert all changes or changes for key

Parse/Parse.m, Tests/Unit/ParseSetupUnitTests.m
Searched over the TODOs and found this. The reason I passed the nil string 'yolo' in the tests is because if you actually pass in nil you'll get a warning.
I don't have too much professional experience with unit tests, please let me know if there's anything wrong with these tests.
=> Checks for nil applicationId and clientKey

Parse/Internal/Object/PFObjectPrivate.h, Parse/PFObject.h, Parse/PFObject.m, Parse/PFUser.m
=> Cleaned up some warnings from the static analyzer

Parse/Internal/Object/Subclassing/PFObjectSubclassInfo.m
Silly mistake. Doesn't cause any real-world problems other than performance and memory usage thankfully. Fixes #125.
=> Added proper caching to PFObjectSubclassInfo.

Parse/Internal/Object/BatchController/PFObjectBatchController.h, Parse/Internal/Object/BatchController/PFObjectBatchController.m, Parse/PFObject.m, Tests/Other/OCMock/OCMock+Parse.h, Tests/Other/OCMock/OCMock+Parse.m, Tests/Unit/ObjectBatchControllerTests.m
- Implemented PFObject.deleteAll through PFObjectBatchController
- Tested against api.parse.com - it works beautifully
- Way better decoupled state, as well as properly using dependency injected command runner
- Fixed bugs around `deleteAll` not properly deleting objects from LDS, as well as not updating the `deleted` property on state
=> Implemented PFObject.deleteAll through PFObjectBatchController.

Parse/PFObject.m, Parse/PFUser.m
Use `self` instead of using `PFObject` or `PFUser` class names.
=> Use 'self' instead of direct class name in PFObject, PFUser.

Parse/Internal/File/PFFile_Private.h, Parse/PFFile.m
- Squashed few methods together
- Added nullability annotations for private header
Compliments #133
=> Cleaned up implementation, added nullability annotations for PFFile.m

Parse/Internal/PFAlertView.m, Parse/Internal/Push/Utilites/PFPushUtilities.m
If used with Cocoapods and minimum deployment target is set to iOS 9 - these two places were providing warnings.
- Added compile time check for PFAlertView
- Made PFPushUtilities use PFAlertView
=> Fixed iOS 9 deprecation warnings in PFAlertView, PFPushUtilities.

Parse/Internal/Commands/CommandRunner/URLSession/Session/TaskDelegate/PFURLSessionJSONDataTaskDelegate.m, Tests/Unit/URLSessionDataTaskDelegateTests.m, Tests/Unit/URLSessionTests.m, Tests/Unit/URLSessionUploadTaskDelegateTests.m
The logic here was slightly wrong - there is a possibility that custom subclasses of `PFObject` will have an `error` column, and that shouldn't be treated as a problem.
This fixes the problem as well as covers any possible scenario of errors (setting the internal server one, where we have no idea what to do with the error).
Fixes #140
=> Fixed error on network requests to Object APIs with 'error' column.

Parse/Internal/KeyValueCache/PFKeyValueCache.m
Previously, PFKeyValueCache was re-reading the file attributes from disk for every cached entry, every time we attempted to set a new entry in the cache.
This had serious performance impact for use-cases where repeated caching was used, as copying and recreating the file attributes dictionary caused lots of system calls and wasted memory.
This diff makes PFKeyValueCache much more optimistic, as it does not re-read attributes from disk if the containing folder has not changed. However, this does introduce a potential race-condition that is noted in the code.
Bottom line: This should improve query caching performance for 99% of use-cases.
Fixes #141.
=> Improved PFKeyValueCache performance and memory usage

Parse/Internal/Analytics/Controller/PFAnalyticsController.h, Parse/Internal/Analytics/Controller/PFAnalyticsController.m, Parse/Internal/ParseManager.m, Tests/Unit/AnalyticsControllerTests.m
- Make `PFAnalyticsController` follow the provider pattern
- Fixed rare main thread stall inside PFAnalyticsController on `trackAppLaunched`
- Fixed rare main thread stall on loading `PFEventuallyQueue`
=> Lazy-load PFEventuallyQueue in PFAnalyticsController.

.travis.yml
Testing new coverage service as a replacement to `coveralls`, let's see how it goes.
=> Add coverage through codecov.io.

.travis.yml
Silly mistake in bash, this fixes it.
=> Update .travis.yml to run codecov.io for both iOS and OS X

Parse/PFQuery.m
In some rare scenarios (e.g. Parse is being torn down), the query will lose all references to it, and the strongify will yield `nil`. When that happens, we cannot read or write to any instance variables in that context.
=> Fixed rare crash in PFQuery related to weakify/strongify.

Parse/Internal/User/AuthenticationProviders/Controller/PFUserAuthenticationController.h, Parse/Internal/User/AuthenticationProviders/Controller/PFUserAuthenticationController.m, Parse/Internal/User/AuthenticationProviders/Providers/Anonymous/PFAnonymousAuthenticationProvider.m, Parse/Internal/User/AuthenticationProviders/Providers/Anonymous/PFAnonymousUtils_Private.h, Parse/Internal/User/AuthenticationProviders/Providers/PFAuthenticationProvider.h, Parse/Internal/User/PFUserPrivate.h, Parse/PFAnonymousUtils.m, Parse/PFUser.m, Tests/Unit/AnonymousAuthenticationProviderTests.m, Tests/Unit/AnonymousUtilsTests.m
This is just restructuring internal APIs that are used for `PFAuthenticationProvider` instance for Facebook/Twitter/Anonymous.
- Restructured and renamed APIs on `PFUser`, `PFAuthenticationProvider`.
- Moved `logInWithAuthType:authData` from `PFUser` into `PFUserAuthenticationController` (yay!)
- Updated `PFAnonymousUtils` and `PFAnonymousAuthenticationProvider` to use new APIs
- Updated tests
=> Restructure authentication provider APIs on PFUser to be able to publicly support them.

.travis.yml, Rakefile
Adding Xcode 7 image, since it's finally supported by Travis.
Please note - we are testing only `ios`/`osx`/`podspecs` with Xcode 7 and not starters or deployment, since we still deploy with Xcode 6.4.
=> Add Xcode 7 to Travis-CI.

Parse/PFCloud.h, Parse/PFConfig.h, Parse/PFConstants.h, Parse/PFFile.h, Parse/PFObject.h, Parse/PFQuery.h, Parse/PFUser.h, ParseStarterProject/OSX/ParseOSXStarterProject-Swift/ParseOSXStarterProject-Swift.xcodeproj/project.pbxproj, ParseStarterProject/iOS/ParseStarterProject-Swift/ParseStarterProject-Swift.xcodeproj/project.pbxproj
- Made all synchronous APIs have `throws` when used from Swift.
- Added backward compatible macro `PF_SWIFT_UNAVAILABLE`, please note that this macro does nothing when compiled with Xcode 6.4, but only works on Xcode 7 (the one that has Swift 2).
After change (Swift 2):
```swift
class PFObject : NSObject {
public func save() throws
}
```
Before change (Swift 2):
```swift
class PFObject : NSObject {
public func save() -> Bool
public func save(error: NSErrorPointer) -> Bool
}
```
Before && After Change (Swift 1.2):
```swift
class PFObject : NSObject {
public func save() -> Bool
public func save(error: NSErrorPointer) -> Bool
}
```
closes #152 
cc @richardjrossiii
=> Make all synchronous APIs have 'throws' in Swift 2.

Tests/Unit/PurchaseControllerTests.m
This test is flaky on Travis because running the command doesn't happen asynchronously, but rather inline (it's mocked to reply with an already completed task) - so sometimes it's completing the overall task faster than it can report progress. Added another expectation for that to make sure that we get a progress callback always.
=> Fix flaky PurchaseControllerTests.testDownloadAsync test.

Parse/PFPush.m, Tests/Unit/PushMobileTests.m
=> Play vibration in PFPush.handlePush() only if default sound is specified.

Parse/PFObject.h, Parse/PFObject.m, Parse/PFUser.h
If these methods fail - they will return `nil`, which makes them `nullable` - annotate accordingly.
Also - replace more instances of direct class names with `instancetype`.
Thank you @adonoho for noticing!
=> Updated nullability annotations and return types for synchronous methods on PFObject.

Parse/Internal/File/Controller/PFFileController.m, Parse/Internal/PFFileManager.h, Parse/Internal/PFFileManager.m, Tests/Unit/FileControllerTests.m
Implemented an old TODO. We already have `copyItemAsyncAtPath:toPath:` in PFFileManager - so simply add a move method.
Also fixed a bug, where we were returning an NSError from continuation block instead of wrapping with BFTask, so the entire pipe was never failing.
=> Added PFFileManager moveItemAsyncAtPath.

Parse/Internal/PFLocationManager.m, Tests/Other/LocationManager/CLLocationManager+TestAdditions.m
These APIs are deprecated and no longer needed since we are iOS 7.0+ and OS X 10.9+.
=> Remove usage of deprecated APIs in PFLocationManager.

Parse/Internal/User/PFUserPrivate.h, Parse/PFUser.m
Replace all exceptions with errors, so we don't crash end applications, but rather fail signup requests.
Contributes to #6
=> Replace exceptions in PFUser.signUp with errors.

Parse/PFObject.m, Parse/PFUser.m
`isKindOfClass:` doesn't work reliably on Classes, since it's an instance method on NSObject, whilst `isSubclassOfClass:` works great (class level method).
This diff also improves logging of `PFUser` subclasses (they now report proper class names).
Fixes #176
=> Fix subclasses of PFObject subclasses failing registration assert.

Parse.xcodeproj/project.pbxproj
For whatever reason `genstrings` is not available in Xcode 6.4 on El Capitan.
Update to use `extractLocStrings` which looks like the same thing.
Tested locally by removing the generated localization.
=> Fixed usage of genstrings on El Capitan under Xcode 6.4.

Parse/PFConstants.h, Parse/PFQuery.h, Parse/PFQuery.m
This adds an ability to do the following on Xcode 7.
```objc
PFQuery<PFUser *> *query = [PFQuery queryWithClassName:@"_User"];
PFUser *user = [query getFirstObject];
PFObject *yolo = [query getFirstObject];
PFInstallation *installation = [query getFirstObject]; // Will put a warning here saying that it's an incompatible type.
```
Please note that we explicitly don't support covariants (discussable) as the best practice is to use a single objc/swift class for any given parse class name, so the following will log a warning:
```objc
PFQuery<PFObject *> *objectQuery = nil;
PFQuery<PFUser *> *query = [PFQuery queryWithClassName:@"_User"];
objectQuery = query; // Warning here saying that the type is incompatible.
```
=> Add backward compatible ObjC generic support for PFQuery.

Parse/Internal/PFHash.m
This is a compiler bug, resulting in undefined behavior. It seems that when clang emits code for a `__block` variable that is of a struct type, it does not actually allocate space for it (lolwut). This should fix that, by using a pointer instead of `__block`.
Fixes #146.
=> Fix PFHash crash w/ undefined behavior.

Configurations/Parse-iOS.xcconfig
Add bitcode only for iphoneos slice.
Closes #75
=> Add bitcode support to precompiled frameworks on iOS 9.

ParseStarterProject/OSX/ParseOSXStarterProject-Swift/ParseOSXStarterProject/AppDelegate.swift, ParseStarterProject/iOS/ParseStarterProject-Swift/ParseStarterProject/AppDelegate.swift
Using `print` instead of `println`, as well as removed code that doesn't work on both version of Swift and replaced with a commented out snippet.
Fixes ParsePlatform/ParseUI-iOS#119
=> Update Starter Projects for Swift 2.

Parse/Internal/Commands/CommandRunner/PFCommandRunningConstants.h, Parse/Internal/Commands/CommandRunner/PFCommandRunningConstants.m, Parse/Internal/Commands/CommandRunner/URLSession/PFURLSessionCommandRunner.m, Parse/Internal/Commands/CommandRunner/URLSession/Session/PFURLSession.h, Parse/Internal/Commands/CommandRunner/URLSession/Session/PFURLSession.m, Parse/Internal/Commands/CommandRunner/URLSession/Session/TaskDelegate/PFURLSessionDataTaskDelegate.h, Parse/Internal/Commands/CommandRunner/URLSession/Session/TaskDelegate/PFURLSessionDataTaskDelegate_Private.h, Parse/Internal/Commands/CommandRunner/URLSession/Session/TaskDelegate/PFURLSessionJSONDataTaskDelegate.m, Parse/Internal/PFLogger.h, Tests/Unit/URLSessionTests.m
- Added another property on every PFURLSessionDataTaskDelegate - `responseString`, which is set only if we have a string to set there
- Added new user info key in PFCommandRunningConstants
- Use `PFLogger.sharedLogger()` to get the log level
- Add user info only if logLevel is set to `PFLogLevelDebug`
cc @wangmengyan95 @grantland
=> Added response body string to network notifications, don't supply any user info if running outside of debug mode.

Parse/Internal/File/Controller/PFFileController.m, Parse/Internal/File/State/PFFileState.h, Parse/Internal/File/State/PFFileState.m, Parse/Internal/PFEncoder.m, Parse/PFFile.m, Tests/Unit/FileStateTests.m
This is still pending backend changes to actually enable https, but just throwing this in, since this is the only client-side change required.
Fixes #12
=> Add https support for PFFiles.

Parse/Internal/Config/PFConfig_Private.h, Parse/Internal/Installation/CurrentInstallationController/PFCurrentInstallationController.m
One could have resulted in a stack smash, and the other would cause issues if we ever linked with C++ anywhere.
=> Fix a few minor undefined behavior issues.

Parse/PFConstants.h
We need to be able to use PF_GENERIC with multiple types (e.g. NSDictionary). Make it varargs.
=> Base work for public Bolts task generics.

Parse/PFSession.h
I guess you could say 
(•\_•) 
( •\_•)>⌐■-■
(⌐■\_■)
Bolts is now in session.
=> Added BFTask generics to header of PFSession

Parse/PFPurchase.h, Parse/PFPurchase.m
=> Fix PFPurchase block nullability annotations.

Parse/Internal/ParseInternal.h, Parse/Internal/User/AuthenticationProviders/Controller/PFUserAuthenticationController.h, Parse/Internal/User/PFUserPrivate.h
Some of these are not required, another piece should only use public imports to avoid duplicates.
=> Cleanup imports for PFAuthenticationProvider.

Parse/Internal/Commands/CommandRunner/PFCommandRunningConstants.h, Parse/Internal/Commands/CommandRunner/PFCommandRunningConstants.m, Parse/Internal/Commands/CommandRunner/URLSession/PFURLSessionCommandRunner.m, Parse/PFConstants.h, Parse/PFConstants.m, Parse/PFNetworkActivityIndicatorManager.m
Rename these notifications and move them into `PFConstants.h`.
cc @grantland @wangmengyan95
=> Publicize network notifications.

Parse.xcodeproj/xcshareddata/xcschemes/Parse-OSX.xcscheme, Parse.xcodeproj/xcshareddata/xcschemes/Parse-iOS.xcscheme
This allows inline code coverage in the IDE. What fun!
=> Enable Xcode7 code-coverage collection for test schemes.

Parse/PFObject.m, Tests/Unit/DecoderTests.m
These dates can come in as NSDates, not just as NSStrings, if they were incapsulated into JSON Object with __type:Date before, like in Cloud Code.
Updated the decoding logic for that.
Fixes #243.
=> Fix decoding of updatedAt/createdAt on PFObject if dates are already decoded.

Parse/PFObject.m, Tests/Unit/ObjectUnitTests.m
- Fixed wrong return type for `deleteInBackground:` if objects array is empty.
- Added tests for all of this.
Fixes #253
=> Fixed crash when using PFObject.deleteAll() with empty array.

Parse/Internal/PFEventuallyPin.m
This caused issues when using the eventually queue, as the eventually pin objects were getting discarded immediately after creation, and never re-fetched from the database afterward.
Fixes #131.
cc @grantland Does this same issue exist on android?
=> Fixed an issue where LDS wouldn't search the whole subtree for objects not yet fetched.

Parse/Internal/User/AuthenticationProviders/Controller/PFUserAuthenticationController.h, Parse/Internal/User/AuthenticationProviders/Controller/PFUserAuthenticationController.m, Parse/Internal/User/AuthenticationProviders/Providers/Anonymous/PFAnonymousAuthenticationProvider.h, Parse/Internal/User/AuthenticationProviders/Providers/Anonymous/PFAnonymousAuthenticationProvider.m, Parse/PFAnonymousUtils.m, Parse/PFUser.m, Parse/PFUserAuthenticationDelegate.h
- Added more generic types
- Cleaned up assertion messages
- Updated constant name to be consistent
- Renamed few methods to be consistent
=> Cleanup PFUser third party authentication.

Parse/Internal/Object/PFObjectPrivate.h, Parse/PFInstallation.m, Parse/PFObject.m
Not coverable with unit tests just yet...
Fixes #261
=> Fixed PFInstallation not updating automatic fields when using PFObject.saveAll().

Parse.xcodeproj/xcshareddata/xcschemes/Parse-OSX.xcscheme
Probably happened during one of our scheme recreations. This makes it very difficult to link against parse for OSX.
=> Fix address sanatizer being enabled for OSX release scheme.

Parse/Internal/Object/BatchController/PFObjectBatchController.m, Parse/Internal/Object/Controller/PFObjectController.m, Parse/Internal/Object/PFObjectPrivate.h, Parse/PFInstallation.m, Parse/PFObject.m, Parse/PFUser.m
- More unity with `validateFetchAsync` and `validateDeleteAsync`
- Converted assertions to errors
Contributes to #6
=> Improved fetch and delete PFObject validation logic.

Parse/PFInstallation.m
=> Add missing backward compatibility to generic type in PFInstallation.

Parse/Internal/Commands/CommandRunner/URLRequestConstructor/PFCommandURLRequestConstructor.m, Parse/Internal/HTTPRequest/PFURLConstructor.h, Parse/Internal/HTTPRequest/PFURLConstructor.m
Since we are not targeting iOS <7.0 and OS X <10.9 - use `NSURLComponents` instead of our own implementation of that.
Fixes #284
=> Use NSURLComponents to construct URLs instead of CFURL.

Parse/PFFile.h
The behavior of initializing a file without anything is undefined.
Simply mark the methods as unavailable, leading to them stop being exposed to Swift and ObjC.
Fixes #234
=> Disable ability to initialize PFFile without data/file/name.

Parse/PFCloud.h, Parse/PFObject.h, Parse/PFUser.h
- `deleteEventually` return NSNumber*
- `enableRevocableSessions` and `logOutInBackground` now don't specify a return type since they are not useful at all (the contract there is to yield `nil`)
cc @grantland
=> Update all NSNull generic types to use NSNumber instead.

Parse/Internal/PFCoreManager.m
I run into an issue where then `becomeInBackground` function returned neither a user object nor an error after a login/logout cycle. I tracked the error down to the `PFUserController` returning `nil` for the `userController` because of what seems to be a copy/paste error when checking for an existing controller.
=> Fix copy/paste error in retrieving userController.

Parse/Internal/PFCoreManager.m, Parse/Internal/User/AuthenticationProviders/Controller/PFUserAuthenticationController.h, Parse/Internal/User/AuthenticationProviders/Controller/PFUserAuthenticationController.m
This will make load of currentUser asynchronous, as well as won't create anonymous user if enabled, and will properly restore auth from a background thread.
Fixes #302
=> Fix initialization of Facebook/Twitter Utils blocking the main thread.

Parse/PFObject.m
By no longer holding a lock while recursing, we allow other threads who may be waiting on the current object to progress before iterating to children of the object, solving some of the deadlocks that we've seen in issues #11, #61, and #299.
This does not necessarily fix the above issues, as we probably still have similar deadlocks elsewhere in the codebase.
This is based on the mutable containers branch until the time comes to land this, as we want some of our users to be able to test this, and mutable containers also contains deadlocks.
cc @grantland
=>     Fixed deadlock in -collectDirtyChildren:

Configurations/Parse-watchOS.xcconfig, Configurations/Shared/Platform/watchOS.xcconfig, Parse.xcodeproj/project.pbxproj, Parse.xcodeproj/xcshareddata/xcschemes/Parse-watchOS.xcscheme, Parse/Resources/Framework-watchOS.plist
Doesn't compile, but is purely target towards watchOS 2.
=> Added basic target for watchOS 2 SDK.

Parse.xcodeproj/project.pbxproj, Parse/Parse.h
Also excluding all internal stuff that powers these.
=> Exclude PFPurchase and PFProduct from watchOS target.

Parse/Internal/PFApplication.h, Parse/Internal/PFApplication.m
No-op in most places, as well as return `nil` for systemApplication.
=> Update PFApplication to compile for watchOS.

Parse.xcodeproj/project.pbxproj, Parse/Internal/Push/Utilites/PFPushUtilities.m
=> Exclude PFPush, PFAlertView, PFNetworkIndicatorManager from watchOS target.

Parse/PFAnalytics.m, Parse/PFConstants.h
=> Fixed PFAnalytics for watchOS.

Parse.xcodeproj/project.pbxproj, Parse/Internal/Installation/Controller/PFInstallationController.h, Parse/Internal/Installation/CurrentInstallationController/PFCurrentInstallationController.h, Parse/Internal/PFCoreManager.m, Parse/Internal/ParseManager.m, Parse/Internal/Push/ChannelsController/PFPushChannelsController.h, Parse/Internal/Push/Manager/PFPushManager.h, Parse/PFInstallation.h, Parse/PFQuery.h, Parse/Parse.m
Mark everything as unavailable, move more things to be unavailable, like PushManager, Push***Controller.
=> Exclude PFInstallation from watchOS target.

Parse.xcodeproj/project.pbxproj, Parse/Internal/Commands/PFRESTPushCommand.h, Parse/Internal/ParseManager.h, Parse/Internal/ParseManager.m, Parse/Internal/Product/ProductsRequestHandler/PFProductsRequestHandler.h, Parse/Internal/Purchase/Controller/PFPurchaseController.h, Parse/Internal/Purchase/PaymentTransactionObserver/PFPaymentTransactionObserver.h, Parse/Internal/Push/Controller/PFPushController.h, Parse/Internal/Push/State/PFMutablePushState.h, Parse/Internal/Push/State/PFPushState.h, Parse/Internal/Push/Utilites/PFPushUtilities.h, Parse/PFProduct.h
=> Exclude PFProduct, PFPush internal things from watchOS target.

Parse/Internal/User/CurrentUserController/PFCurrentUserController.m
We have few checks on auth restoration, which happens on loading the sensitive user data from keychain.
These checks rely on the fact that the receiver (instance of PFUser) responds `YES` to `isCurrentUser`.
Basically - move the `isCurrentUser` change to one step closer. Doesn't change the flow, but fixes a potential bug with third party authentication.
=> Fixed currentUser not restoring authentication on load from disk.

Parse.xcodeproj/project.pbxproj
=> Make sure we compile Bolts with watchOS support.

Parse/PFAnalytics.h, Parse/PFAnalytics.m
Dimensions are enforced to be String->String.
This change also sync implementation and header file for PFAnalytics.
=> Add ObjC generics to collections in PFAnalytics public header.

Parse/PFPush.h, Parse/PFPush.m
Push supports only Installation queries, so make sure we specify that in header.
Also added generic type to `channels`, since that one can be only strings.
=> Add ObjC generics to collections/queries in PFPush public header.

Parse/PFQuery.h
- Selected keys can only be strings.
- Specify generic type when creating an `orQuery` (the array should always be with queries)
- Specify generic type when sorting using multiple descriptors
=> Add ObjC generics to collections in PFQuery public header.

Parse/PFObject.h
- Creating an object can only be made with a dictionary of String to AnyObject (all keys should be strings)
- `allKeys` are only Strings
- Save/Fetch/Delete/Pin/Unpin collection methods support only PFObjects. :grin:
=> Add ObjC generics support to collections in PFObject public header.

Parse/PFFile.h, Parse/PFFile.m, Tests/Unit/FileUnitTests.m
Switching to errors provides a more consistent interface, as we should never use exceptions in objective-c except for unrecoverable errors.
Fixes #338.
=> Use errors instead of exceptions when creating a PFFile.

Parse.xcodeproj/project.pbxproj, Parse/Internal/File/Controller/PFFileController.m, Parse/Internal/File/FileDataStream/PFFileDataStream.h, Parse/Internal/File/FileDataStream/PFFileDataStream.m, Tests/Unit/FileDataStreamTests.m
This is an NSInputStream proxy that is used for file downloads while concurrently reading and writing to a file. This allows us to truly stream from parse using `-[PFFile getDataDownloadStreamInBackground]`, whereas before it had the potential to break if you consumed it too fast.
=> Added PFFileDataStream for streaming file Downloads.

Tests/Unit/AnalyticsUnitTests.m
Simply ignore the warnings, since these are checking that we have an extra validation logic for incompatible types.
=> Fix warnings in AnalyticsTests when building with Xcode 7.

Parse/PFFile.m
If error pointer is `nil` here - we are going to have a null dereference.
=> Fixed potential null dereference when creating files with nil error.

Parse/Internal/Config/Controller/PFCurrentConfigController.m, Parse/Internal/PFJSONSerialization.h, Parse/Internal/PFJSONSerialization.m
Don't load into `NSData`, then decode, but rather decode from stream directly.
Should improve performance of loading `PFConfig` from disc.
=> Improve PFConfig loading from disc performance by using JSON stream from file.

Parse/Internal/PFInternalUtils.m, Parse/Parse.m
If `PFInternalUtils` is initialized after the first call to `PFNetworkActivityIndicatorManager.sharedManager()` - potentially we are going to force-enable the manager once again.
This fixes it by moving enabling of the indicator straight after Parse is initialized.
Fixes #366
=> Fix late initialization of NetworkActivityIndicatorManager.

Parse/PFObject+Subclass.h, Parse/PFSubclassing.h, Parse/PFUser.h
In case someone imports this without a query - this should have generics.
=> Add generics to all instances of class forwarded PFQuery.

Parse/PFObject.h
watchOS is short-lived, so eventually doesn't quite make much sense.
Maybe add capability for it later, but for now - simply mark as unavailable.
=> Mark saveEventually/deleteEventually as unavailable on watchOS.

Parse/Internal/PFInternalUtils.h, Parse/Internal/PFInternalUtils.m, Parse/Internal/ParseManager.m, Parse/Parse.h, Parse/Parse.m
No PFInstallation, PFProduct, PFPush on watchOS.
=> Update few imports to unbreak watchOS target.

Parse.xcodeproj/project.pbxproj
It's missing from the target, but looks like it still would be useful.
=> Add missing FileDataStream to watchOS target.

Rakefile, Scripts/xctask/build_framework_task.rb
Finally - adding this to Travis-CI so we can monitor breakages.
=> Add Parse watchOS deployment testing to Travis.

Parse/Internal/Object/Subclassing/PFObjectSubclassingController.m
Somehow missed this bit.
Made sure we don't import in any other place by running workspace search, for installation, push, purchase, product.
=> Remove useless imports in PFObjectSubclassingController.

Parse/Parse.h
This APIs don't quite make sense on watchOS, since there is no ability to use main app + extensions on watchOS.
=> Mark extension-specific APIs as unavailable for watchOS.

Parse/Internal/PFJSONSerialization.m
You can still create NSInputStream from no file on disc, but it will fail inside NSJSONSerialization - this fixes that issue.
=> Don't try to decode JSON object from stream if there is no such file.

Parse/Internal/HTTPRequest/PFURLConstructor.m
This looks like a typo, and we didn't catch it in testing, since iOS 8/9 reports empty string instead of `nil`, whilst iOS 7 - reports `nil`.
Fixes #388
=> Fix URL construction on iOS 7.

Parse/Internal/HTTPRequest/PFHTTPURLRequestConstructor.m, Tests/Unit/CommandURLRequestConstructorTests.m
THere is no `utf8` charset, only `utf-8`. Thanks to @gfosco for catching this.
=> Fix default content type for JSON URL Requests.

Parse/Internal/Commands/CommandRunner/URLSession/Session/PFURLSession.m, Parse/Internal/Installation/Controller/PFInstallationController.m, Parse/Internal/Installation/CurrentInstallationController/PFCurrentInstallationController.m, Parse/Internal/LocalDataStore/OfflineStore/PFOfflineStore.m, Parse/Internal/LocalDataStore/SQLite/PFSQLiteDatabase.m, Parse/Internal/Object/OperationSet/PFOperationSet.m, Parse/Internal/PFEventuallyPin.m, Parse/Internal/PFInternalUtils.m, Parse/Internal/PFKeychainStore.m, Parse/Internal/PFLogger.m, Parse/Internal/PFMulticastDelegate.h, Parse/Internal/PFMulticastDelegate.m, Parse/Internal/PFPinningEventuallyQueue.m, Parse/Internal/Purchase/PaymentTransactionObserver/PFPaymentTransactionObserver.m, Parse/Internal/Query/Controller/PFOfflineQueryController.m, Parse/Internal/Query/PFQueryPrivate.h, Parse/Internal/Query/Utilities/PFQueryUtilities.m, Parse/Internal/User/Controller/PFUserController.m, Parse/Internal/User/CurrentUserController/PFCurrentUserController.m, Parse/PFConfig.m, Parse/PFFile.h, Parse/PFGeoPoint.m, Parse/PFObject.h, Parse/PFQuery.h, Parse/PFQuery.m, Parse/PFRelation.m, Parse/PFUser.h, Tests/Other/TestCases/TestCase/PFTestCase.m
Split into multiple commits, but will squash together after review.
Depends on #403
=> Fix all new warnings.

Parse/Internal/PFCoreManager.m, Parse/Internal/ParseManager.m
=> Safeguard unavailable imports when building for watchOS.

Parse.dev.podspec, Rakefile
We don't want to ship this in the main podspec just yet, but still be able to test it on Travis and if someone wants to target it from source - it will work beautifully.
=> Add development version of the Podspec with watchOS 2 support.

Parse/Internal/Object/PFObjectPrivate.h, Parse/PFObject.m, Parse/PFUser.m
We didn't actually need to hold the lock here, and if we did, another thread could have acquired these locks in another order, causing a deadlock.
Should help to fix #398, #11, and a few others.
=> Fix a potential deadlock that could occur when encoding for REST.

Parse/Internal/Object/PFObjectPrivate.h, Parse/PFObject.m, Parse/PFUser.m
This is stored as a count aka integer in the database, make sure it's explicit the same way on PFObject.
=> Make sure we always pass an int for deletingEventuallyCount.

Parse/PFObject.m, Parse/PFUser.m
No need for user.lock here, since we removed the super class one as well and we are guaranteed to be passed in a copy of opSetQueue.
Has a potential to resolve yet another deadlock specifically when using users.
=> Remove potential deadlock from encoding PFUser.

Parse.xcodeproj/project.pbxproj, Parse/Internal/Commands/PFRESTPushCommand.h, Parse/Internal/ParseManager.h, Parse/Internal/ParseManager.m, Parse/Internal/Push/ChannelsController/PFPushChannelsController.h, Parse/Internal/Push/Controller/PFPushController.h, Parse/Internal/Push/Manager/PFPushManager.h, Parse/Internal/Push/State/PFMutablePushState.h, Parse/Internal/Push/State/PFPushState.h, Parse/Internal/Push/Utilites/PFPushUtilities.h, Parse/PFConstants.h, Parse/PFPush.h
- Marked all PFPush classes as unavailable on tvOS
- Removed few more things from tvOS target compilation phase.
=> Mark all PFPush* things as unavailable for tvOS.

Parse.xcodeproj/project.pbxproj, Parse/Internal/Installation/Controller/PFInstallationController.h, Parse/Internal/Installation/CurrentInstallationController/PFCurrentInstallationController.h, Parse/Internal/PFCoreManager.m, Parse/Internal/ParseManager.m, Parse/PFInstallation.h, Parse/Parse.m
- Mark PFInstallation, and relevant classes as unavailable on tvOS
- Remove all of them from targets build phase
Depends on #440 
=> Disable PFInstallation for tvOS target.

Parse.xcodeproj/project.pbxproj, Parse/PFNetworkActivityIndicatorManager.h, Parse/PFNetworkActivityIndicatorManager.m
=> Disable PFNetworkActivityIndicatorManager on tvOS.

Parse/Internal/Object/PFObjectPrivate.h, Parse/Internal/PFInternalUtils.h, Parse/Internal/PFInternalUtils.m, Parse/PFObject.m, Parse/PFUser.m
Closes #97 
Contributes to #32
=> Removed 'mutable containers' functionality.

Parse/PFUser.h, Parse/PFUser.m, Parse/PFUserAuthenticationDelegate.h
These were missing - add them. As well as run clang-format on entire PFUser.
=> Add generic types to PFUser login/link methods.

Parse/Internal/File/Controller/PFFileStagingController.m
There is a guarantee that files are not going to be deleted in caches folder if the app is running, and since these files don't quite make sense after app restart (they hold a pointer) - let's move them to caches folder.
Also, this contributes to #250, since data is not persistent on tvOS and we can now store it properly in Caches folder.
=> Store staged PFFiles in cache directory.

Parse/PFUser.m
Fixes #467.
Used this piece of code to test:
```objc
- (void)testLinkWithStripsNewDataOnFail {
id mock = PFStrictProtocolMock(@protocol(PFUserAuthenticationDelegate));
[PFUser registerAuthenticationDelegate:mock forAuthType:@"a"];
OCMStub([mock restoreAuthenticationWithAuthData:@{ @"a" : @"b" }]).andReturn(YES);
PFUser *user = [PFUser user];
user.username = @"yolo";
user.password = @"yarr";
XCTAssertTrue([user signUp:nil]);
XCTestExpectation *linkExpectation = [self expectationWithDescription:@"link user"];
[[user linkWithAuthTypeInBackground:@"a" authData:@{ @"a" : @"b" }] continueWithBlock:^id(BFTask<NSNumber *> *task) {
XCTAssertTrue(task.faulted);
XCTAssertNotNil(task.error);
[linkExpectation fulfill];
return nil;
}];
[self waitForTestExpectations];
XCTAssertFalse([user …
```
=> Fix an issue with persistent bad authData on failure to link a user.

Parse/Internal/Config/Controller/PFConfigController.h, Parse/Internal/Config/Controller/PFConfigController.m, Parse/Internal/Config/Controller/PFCurrentConfigController.h, Parse/Internal/Config/Controller/PFCurrentConfigController.m, Parse/Internal/PFCoreManager.m, Tests/Unit/ConfigControllerTests.m, Tests/Unit/CurrentConfigControllerTests.m
=> Refactor PFConfigController, PFCurrentConfigController to use dataSource for all providers.

Parse/Internal/CloudCode/PFCloudCodeController.h, Parse/Internal/CloudCode/PFCloudCodeController.m, Parse/Internal/PFCoreManager.m, Tests/Unit/CloudCodeControllerTests.m
Unifying with other controllers.
=> Use dataSource pattern to get command runner in PFCloudCodeController.

Parse/Internal/Commands/PFRESTQueryCommand.m
Sort the keys that come from a set.
Fixes #478.
=> Make sure our cacheKey for query commands is generated in consistent order.

Parse/Internal/Installation/PFInstallationPrivate.h, Parse/Internal/Push/PFPushPrivate.h, Parse/PFInstallation.h, Parse/Parse.m
=> Safeguard and remove imports for private headers of PFPush, PFInstallation for watchOS, tvOS.

Parse.xcodeproj/project.pbxproj, Parse/Internal/PFDataProvider.h, Parse/Internal/ParseManager.h, Parse/Internal/ParseManager.m, Parse/Internal/Persistence/Group/PFFilePersistenceGroup.h, Parse/Internal/Persistence/Group/PFFilePersistenceGroup.m, Parse/Internal/Persistence/Group/PFPersistenceGroup.h, Parse/Internal/Persistence/Group/PFUserDefaultsPersistenceGroup.h, Parse/Internal/Persistence/Group/PFUserDefaultsPersistenceGroup.m, Parse/Internal/Persistence/PFPersistenceController.h, Parse/Internal/Persistence/PFPersistenceController.m
- PFPersistenceController
- PFFilePersistenceGroup (iOS/OSX/watchOS)
- PFUserDefaultsPersistenceGroup (tvOS)
Also fully migrated our applicationId storage to be based purely on PFPersistenceController with validation and merrymaking.
=> Reimplement file persistence via PFPersistenceController + PFPersistenceGroup, migrate applicationId storage to it.

Parse/Internal/Config/Controller/PFConfigController.h, Parse/Internal/Config/Controller/PFConfigController.m, Parse/Internal/Config/Controller/PFCurrentConfigController.h, Parse/Internal/Config/Controller/PFCurrentConfigController.m, Parse/Internal/PFCoreManager.h, Tests/Unit/CurrentConfigControllerTests.m
This moves all PFConfig related code to use persistence groups instead of file manager APIs.
Including PFCurrentConfigController, PFConfigController.
Depends on #492.
=> Move PFConfig to use persistence groups.

Parse/Internal/PFDevice.m
Changes made according to the comments in #503
=> Make PFDeviceSysctlByName more safe and easy to maintain

Tests/Unit/InstallationIdentifierUnitTests.m
Porting a private test. This could safely live here.
=> Add thread safety tests for InstallationIdentifierStore.

Parse/Internal/PFFileManager.h, Parse/Internal/PFFileManager.m, Parse/Internal/ParseManager.m
This migration was first implemented in version 0.4.38 of the iOS SDK, according to the version notes and was released around Feb 2012.
We are going to remove this code, so any application upgrading from a version < 0.4.38 will not migrate the data any more.
Since 0.4.38 and 1.10.0 (next version) has at least one major version difference, I feel we should make this call.
Please note that this is going to improve the performance of reading anything from disk, as we are not going to hit the lookup of deprecated path anymore.
Plus, it's going to get so much easier to maintain, as we move to Persistence Groups (disk/UserDefaults for tvOS).
cc @grantland @stanleyw @hallucinogen
=> Remove any migration of data from old deprecated location.

Parse/Internal/Commands/CommandRunner/URLRequestConstructor/PFCommandURLRequestConstructor.h, Parse/Internal/Commands/CommandRunner/URLRequestConstructor/PFCommandURLRequestConstructor.m, Parse/Internal/Commands/CommandRunner/URLSession/PFURLSessionCommandRunner.m, Parse/Internal/Installation/CurrentInstallationController/PFCurrentInstallationController.m, Parse/Internal/Installation/InstallationIdentifierStore/PFInstallationIdentifierStore.h, Parse/Internal/Installation/InstallationIdentifierStore/PFInstallationIdentifierStore.m, Parse/Internal/Installation/InstallationIdentifierStore/PFInstallationIdentifierStore_Private.h, Parse/Internal/ParseManager.m, Tests/Unit/CommandURLRequestConstructorTests.m, Tests/Unit/ConfigControllerTests.m, Tests/Unit/FileUnitTests.m, Tests/Unit/InstallationIdentifierUnitTests.m, Tests/Unit/URLSessionCommandRunnerTests.m
- Rewrite InstallationIdentifierStore to use persistence groups and use tasks.
- Update CommandURLRequestContructor accommodating the change, also convert to task-based system.
- Update CurrentInstallationController accommodating the change.
- Update all the tests.
=> Rewrite InstallationIdentifierStore to use Persistence groups and be fully async.

Tests/Unit/InstallationIdentifierUnitTests.m
Tests got broken due to merge of 2 pull requests.
This will unbreak them.
=> Unbreak InstallationIdStore tests.

Parse/Parse.h
Since there is no persistent storage on tvOS - disable Local Datastore for now.
=> Disable Local Datastore on tvOS.

Parse/PFACL.h, ParseStarterProject/OSX/ParseOSXStarterProject-Swift/ParseOSXStarterProject/AppDelegate.swift, ParseStarterProject/iOS/ParseStarterProject-Swift/ParseStarterProject/AppDelegate.swift
Realized that we can use properties for this, instead of having 2 distinct methods.
Maps waaaay better to Swift code.
=> Convert getters/setters of public read/write access on PFACL to properties.

Parse/Internal/LocalDataStore/SQLite/PFSQLiteDatabase.m, Parse/Internal/LocalDataStore/SQLite/PFSQLiteDatabaseResult.h, Parse/Internal/LocalDataStore/SQLite/PFSQLiteDatabaseResult.m, Parse/Internal/LocalDataStore/SQLite/PFSQLiteStatement.h, Parse/Internal/LocalDataStore/SQLite/PFSQLiteStatement.m, Parse/Internal/ThreadSafety/PFThreadsafety.h
I think this is what was causing the crashes seen in #290, but I'm not 100% sure.
At the very least, accessing them this way was in violation of the SQLite spec.
=> Made all accesses to PFSQLiteDatabaseResult & Statement thread-safe.

Parse/Internal/PFDataProvider.h
This one should be annotated with `null_resettable`, as we will always load it if it's nil.
=> Properly annotate pinningObjectStore provider property.

Parse/Internal/Object/FilePersistence/PFObjectFilePersistenceController.h, Parse/Internal/Object/FilePersistence/PFObjectFilePersistenceController.m, Parse/Internal/User/CurrentUserController/PFCurrentUserController.h, Parse/Internal/User/CurrentUserController/PFCurrentUserController.m, Tests/Unit/ObjectFilePersistenceControllerTests.m
- PFUser.logOut() now uses persistence groups
- Added method for removing object to PFObjectFilePersistenceController
- Added test for new method
- Removed requirement for PFFileManager from PFCurrentUserController
=> Move PFUser.logOut() to use persistence groups.

Parse/Internal/Installation/CurrentInstallationController/PFCurrentInstallationController.h, Parse/Internal/Installation/CurrentInstallationController/PFCurrentInstallationController.m
- Use `PFObjectFilePersistenceController.removePersistentObjectAsyncForKey()`
- Remove `PFFileManager` requirement
Depends on #543
=> Move private clearing of CurrentInstallation to use persistence groups.

Parse/Internal/Installation/CurrentInstallationController/PFCurrentInstallationController.m, Parse/Internal/LocalDataStore/OfflineQueryLogic/PFOfflineQueryLogic.m, Parse/Internal/LocalDataStore/OfflineStore/PFOfflineStore.m, Parse/Internal/Object/BatchController/PFObjectBatchController.m, Parse/Internal/PFInternalUtils.m, Parse/PFObject.h, Parse/PFObject.m, Parse/PFSubclassing.h, Tests/Unit/ObjectBatchControllerTests.m, Tests/Unit/ObjectFileCoderTests.m, Tests/Unit/ObjectFileCodingLogicTests.m, Tests/Unit/ObjectSubclassPropertiesTests.m, Tests/Unit/ObjectUnitTests.m, Tests/Unit/UserFileCodingLogicTests.m
Convert to a property with custom getter for backward compatability.
=> Convert isDataAvailable, isDirty, allKeys methods in PFObject to properties.

Parse/PFNetworkActivityIndicatorManager.h, Parse/PFNetworkActivityIndicatorManager.m
- Return specific class not `instancetype` for singleton
- Use property access instead of method calls
=> Convert PFNetworkActivityIndicatorManager to modern Obj-C.

Parse/Internal/PFEncoder.m, Parse/PFFile.h, Parse/PFFile.m, Tests/Unit/FileUnitTests.m
- Convert methods to properties with custom getters for backwards compatibility
- Update all usages of methods to properties
=> Convert isDataAvailable, isDirty methods in PFFile to properties.

Parse.podspec, Parse.xcodeproj/project.pbxproj, Parse/Internal/PFMemoryEventuallyQueue.h, Parse/Internal/PFMemoryEventuallyQueue.m, Parse/Internal/ParseManager.m, Parse/PFConstants.h
- Created a new class that implements PFEventuallyQueue
- Use in-memory store only for all the commands
- Use the class if compiling for tvOS
=> Create in-memory eventually queue for analytics events on tvOS.

Parse/Internal/PFDevice.m
The string that we get back from `sysctlbyname` is usually null-terminated, but we were not handling that case.
This will handle both cases.
=> Fix null-termination of system call on getting the full os version.

Parse/Internal/File/Controller/PFFileController.m, Parse/PFFile.m
- Report an error when trying to download a file that doesn't have a URL
- Report an error when trying to upload a file without locally available content (aka no `stagedFilePath`)
- Properly return `NO` for the unsaved files without local content in `PFFile.dataAvailable` property
Fixes #528.
=> Fix crash on trying to getData/save a PFFile without local data.

Parse/Internal/Product/ProductsRequestHandler/PFProductsRequestHandler.m
Add more handling for the reset of `delegate` back to `nil`, since it looks like StoreKit is not ARC.
Also, added better API handling to make sure we do not re-create a TaskCompletionSource for the same products request.
Closes #537
=> Safeguard API usage and delegate reset in ProductsRequestHandler.

Parse/PFInstallation.h, Parse/PFInstallation.m
This could only ever be a `NSString *`, specify that.
=> Specialize generic type on 'channels' key of PFInstallation.

Parse.xcodeproj/project.pbxproj, Rakefile
Also, enables everyone to simply `rake build:tvos`
=> Add tvOS framework to deployment testing.

Parse/Internal/LocalDataStore/SQLite/PFSQLiteDatabaseResult.m
Introduced in commit 9757503, simple type-cast warning. Only seems to appear when compiling for testing though.
=> Fixed warning in SQLiteDatabaseResult.

Parse/PFObject.h
=> Disable saveEventually/deleteEventually on tvOS.

Parse/Internal/Push/ChannelsController/PFPushChannelsController.h, Parse/Internal/Push/ChannelsController/PFPushChannelsController.m, Parse/PFPush.h, Parse/PFPush.m
Add missing generic type to the public method and the entire pipe.
=> Add missing generic type to PFPush.getSubscribedChannels().

Parse/Internal/PFDateFormatter.m
This improves creation of string from dates by ~5 times, by using sqlite directly instead of generic NSDateFormatter.
As a result of this improvement:
- 5-10% win in LDS performance on pinning (I am serious, there is a huge ton of time spent here)
- huge performance gain on encoding any JSON that has our dates in it, say for any network request
Contributes to #32, as it improves LDS perf.
Now, onto notes - I intentionally am not resetting the binding on the statements,
as there is slight performance gain there (about 5% compared to resetting them every time).
Couldn't come up with implications on not doing this, as I feel it's safe to do it in this use-case.
=> Improve performance of string from date creation.

Parse/Internal/BFTask+Private.h, Parse/Internal/BFTask+Private.m, Parse/Internal/LocalDataStore/OfflineStore/PFOfflineStore.m, Parse/Internal/LocalDataStore/SQLite/PFSQLiteDatabase.h, Parse/Internal/LocalDataStore/SQLite/PFSQLiteDatabase.m
Doesn't really add any performance improvements just yet, but this is a waay better API that will guarantee us thread-safety, since the only access to SQLite should be in these blocks.
=> Add and use block-based API for querying SQLite database.

Parse/Internal/LocalDataStore/OfflineStore/PFOfflineStore.m
Contributes to #32 by improving performance about ~20% compared to previous one on basic queries.
(using a benchmark with 1000 objects in LDS)
Batch pointer fetch by 25 objects at once, instead of running 25 separate queries.
We can do more in this space by parallelizing the fetch further, but this is the first step into this direction.
Depends on #603
=> Batch pointer fetch by 25 objects on querying from LDS.

Parse/Internal/Commands/CommandRunner/URLRequestConstructor/PFCommandURLRequestConstructor.m
Contributes to #179, #250.
cc @stanleyw
=> Specify the proper client version header value for watchOS, tvOS.

Parse/Internal/Object/PFObjectPrivate.h, Parse/PFObject.h
These ivars are very much private and should not be exposed.
Remove them from public header.
=> Remove public declarations of ivars on PFObject.

Parse/PFSubclassing.h
All other methods of PFSubclassing are optional and the default implementation is provided by PFObject.
=> Mark +parseClassName as required method.

Parse/Internal/LocalDataStore/SQLite/PFSQLiteDatabase.m
There is a leak here, we are referencing an ivar, which is implicitly referencing `self` inside a `BFExecutor`, which is also retained by `self`.
Fixed simply by using a shared queue pointer, which eliminates reference to `self`. Verified via Instruments.app both on iPhone 6S and Simulator.
Fixes #626.
=> Fix memory leak in PFSQLiteDatabase.

ParseStarterProject/watchOS/ParseStarterProject-Swift/ParseStarter Extension/Info.plist, ParseStarterProject/watchOS/ParseStarterProject-Swift/ParseStarter/Info.plist, ParseStarterProject/watchOS/ParseStarterProject-Swift/Resources/Info.plist, Rakefile
=> Add watchOS SDK/starters package creation to Rakefile.

Parse/Resources/Parse-tvOS.Info.plist, ParseStarterProject/tvOS/ParseStarterProject-Swift/ParseStarter/Info.plist, Rakefile
Depends on #632, because merge conflicts are painful.
=> Add tvOS SDK/starters package creation to Rakefile.

Parse/Internal/Commands/CommandRunner/URLSession/Session/TaskDelegate/PFURLSessionFileDownloadTaskDelegate.m, Parse/Internal/Commands/CommandRunner/URLSession/Session/TaskDelegate/PFURLSessionUploadTaskDelegate.m, Parse/PFAnalytics.m, Parse/PFConstants.h
These imports are quite bad - removing them.
Since in all public APIs - we always import a framework if it's required for any of the types in the header - no public impact.
=> Remove useless and crazy imports in PFConstants.

.travis.yml, Rakefile
It's finally available since 11PM PST yseterday.
=> Use Xcode 7.2 for Travis-CI.

ParseStarterProject/watchOS/ParseStarterProject-Swift/ParseStarter-Swift.xcodeproj/project.pbxproj, ParseStarterProject/watchOS/ParseStarterProject-Swift/ParseStarter-Swift.xcodeproj/xcshareddata/xcschemes/ParseWatchStarter-iOS.xcscheme, ParseStarterProject/watchOS/ParseStarterProject-Swift/ParseStarter-Swift.xcodeproj/xcshareddata/xcschemes/ParseWatchStarter-watchOS.xcscheme, ParseStarterProject/watchOS/ParseStarterProject-Swift/ParseStarterProject/AppDelegate.swift, ParseStarterProject/watchOS/ParseStarterProject-Swift/Resources/Images.xcassets/AppIcon.appiconset/Contents.json, Rakefile
Required for #179.
- Improves deployment by moving the Bootstrap script to scheme instead of target dependency.
- Updated Rakefile packaging for watchOS starter to pull both iOS and watchOS frameworks.
- Updated PFACL API usage in watchOS starter.
Tested with `rake package:starters` multiple times - it produces the proper ones now.
=> Improved and cleanup deployment for watchOS starter project.

Parse/Internal/ACL/DefaultACLController/PFDefaultACLController.h, Parse/Internal/ACL/DefaultACLController/PFDefaultACLController.m, Parse/Internal/PFCoreDataProvider.h, Parse/Internal/PFCoreManager.h, Parse/Internal/PFCoreManager.m, Parse/PFACL.m, Tests/Unit/DefaultACLControllerTests.m
This also adds assert on setting the default ACL without initializing Parse.
=> Convert DefaultACLController to instance on CoreManager.

Parse/PFObject.h
Removed a line about a callback on the method version that doesn't have a callback.
Should something be added about the circumstances under which the BFTask completes/errors?
=> Documentation update

Parse.xcodeproj/project.pbxproj, Tests/Unit/ACLDefaultTests.m, Tests/Unit/ACLTests.m, Tests/Unit/FileControllerTests.m, Tests/Unit/ObjectFilePersistenceControllerTests.m, Tests/Unit/ObjectLocalIdStoreTests.m, Tests/Unit/OfflineQueryControllerTests.m, Tests/Unit/PushChannelsControllerTests.m, Tests/Unit/SQLiteDatabaseTest.m, Tests/Unit/SessionControllerTests.m
This PR cleanes up and converts many tests to be pure unit, meaning they don't need a Parse to be initialized, but rather depend on the injected configuration/dependencies to run.
=> Cleanup tests and convert many of them to pure unit tests.

Parse/Internal/ParseModule.m, Tests/Unit/ParseModuleUnitTests.m
By lifting the `dispatch_async` outside of the module collection enumeration, it allows for fewer local variable caputres, improving perfromance, as well as not requiring multiple flushes of the main dispatch queue to execute.
=> Make ParseModuleCollection initialization not dispatch_async multiple times.

Parse.xcodeproj/project.pbxproj, Parse/Internal/Commands/CommandRunner/URLSession/PFURLSessionCommandRunner.h, Parse/Internal/Commands/CommandRunner/URLSession/PFURLSessionCommandRunner.m, Parse/Internal/ParseClientConfiguration_Private.h, Parse/Internal/ParseInternal.h, Parse/Internal/ParseManager.h, Parse/Internal/ParseManager.m, Parse/Parse.h, Parse/Parse.m, Parse/ParseClientConfiguration.h, Parse/ParseClientConfiguration.m, Tests/Unit/ParseClientConfigurationTests.m
Old initialization looked somewhat outdated, our new APIs allow a usage similar to this:
```objc
[Parse initializeWithConfiguration:[ParseClientConfiguration configurationWithBlock:^(ParseClientConfiguration *configuration) {
configuration.applicationId = ...;
configuration.clientKey = ...;
configuration.localDatastoreEnabled = ... ;
// Data sharing config, etc.
}];
```
```swift
Parse.initializeWithConfiguration(ParseClientConfiguration() {
$0.applicationId = ""
$0.clientKey = ""
$0.localDatastoreEnabled = true
// etc.
})
````
We believe that this provides a much cleaner interface for initialization. Please feel free to comment below on any feedback that you may have on this
------
Our current SDK initialization is lackluster in that it's split across multiple classes, files, and method …
=> Add better, more flexible APIs for SDK initialization.

Parse/PFObject.m, Tests/Unit/ObjectUnitTests.m
The default implementation invokes setValue:forKey: for each key-value pair, substituting `nil` for `NSNull` values in keyedValues.
Overwrite and invoke everything directly, without substituing `nil` for `NSNull`.
Fixes #667.
=> Fix usage of PFObject.setValuesForKeysWithDictionary: with 'NSNull' keys.

Parse/Internal/Commands/CommandRunner/PFCommandRunning.h, Parse/Internal/Commands/CommandRunner/URLRequestConstructor/PFCommandURLRequestConstructor.h, Parse/Internal/Commands/CommandRunner/URLRequestConstructor/PFCommandURLRequestConstructor.m, Parse/Internal/Commands/CommandRunner/URLSession/PFURLSessionCommandRunner.h, Parse/Internal/Commands/CommandRunner/URLSession/PFURLSessionCommandRunner.m, Parse/Internal/PFInternalUtils.m, Parse/Internal/PFReachability.m, Parse/Internal/ParseManager.h, Parse/Internal/ParseManager.m, Parse/Internal/Parse_Private.h, Parse/PFConstants.h, Parse/PFConstants.m, Parse/Parse.m, Tests/Unit/CommandURLRequestConstructorTests.m, Tests/Unit/CommandUnitTests.m, Tests/Unit/URLSessionCommandRunnerTests.m
This also adds moves the `/1` logic to the constant itself, instead of hard-coding it on URLRequest creation time. 
Depends on #664
=> Inject parse api server url instead of referencing a global constant.

Parse/Internal/HTTPRequest/PFURLConstructor.m, Tests/Unit/URLConstructorTests.m
We rely on this when requesting file saves - which will fail with a different error if there is a forward slash in the end (filename is invalid, instead of resource not found).
=> Fixed construction of urls with path that ends with forward slash.

Parse.xcodeproj/project.pbxproj, Parse/Internal/Object/PFObjectPrivate.h, Parse/PFAnonymousUtils+Deprecated.h, Parse/PFAnonymousUtils.h, Parse/PFAnonymousUtils.m, Parse/PFCloud+Deprecated.h, Parse/PFCloud.h, Parse/PFCloud.m, Parse/PFFile+Deprecated.h, Parse/PFFile.h, Parse/PFFile.m, Parse/PFObject+Deprecated.h, Parse/PFObject.h, Parse/PFObject.m, Parse/PFPush+Deprecated.h, Parse/PFPush.h, Parse/PFPush.m, Parse/PFQuery+Deprecated.h, Parse/PFQuery.h, Parse/PFQuery.m, Parse/PFUser+Deprecated.h, Parse/PFUser.h, Parse/PFUser.m, Parse/Parse.h, Tests/Unit/AnonymousUtilsTests.m, Tests/Unit/CloudUnitTests.m, Tests/Unit/FileUnitTests.m, Tests/Unit/PushUnitTests.m, Tests/Unit/QueryUnitTests.m
This moves all the declarations into class extensions (categories) as well as adds `deprecated` attribute to all methods that end with `...target:selector:`. These methods are pretty much useless and are deprecated in favor of either block-based callbacks or task-based approach.
=> Deprecate target:selector: asynchronous methods in all public classes.

Parse/ParseClientConfiguration.h
- Use the proper syntax for marking piece of documentation.
- Add `@mark` to split configuration into few pieces.
=> Improve and fix documentation of ParseClientConfiguration.

README.md
Looks like Travis default badge is using any latest branch available, which doesn't quite suite us, since we care only about `master`.
Use the `shields.io` version of it that supports branches.
=> Use shields.io badge for Travis-CI

Parse/PFQuery.h
Could easily be a property instead of a method.
=> Convert 'hasCachedResult' on PFQuery to a property.

Parse/ParseClientConfiguration.h
These properties are not available on tvOS/watchOS, but were not marked as such.
Not marking the `readonly` counterpart on `ParseClientConfiguration`, as that part is not required as well as will prevent us from using them internally without extra changes.
=> Mark unavailable properties for tvOS/watchOS as such in ParseMutableClientConfiguration.

Parse/Internal/Object/PinningStore/PFPinningObjectStore.h, Parse/Internal/Object/PinningStore/PFPinningObjectStore.m, Parse/PFObject.m, Tests/Unit/PinningObjectStoreTests.m
Due to the fact that some of these methods might return earlier - there could be `nil` result set on `pin`/`unpin` result tasks. This fixes the issue by enforcing generic types across both `PFPinningObjectStore` and `PFObject` implementation.
Contributes to #604, #563
=> Fixed potential issue with wrong result type set on pin/unpin methods of PFObject.

ParseStarterProject/iOS/ParseStarterProject-Swift/ParseStarterProject-Swift.xcodeproj/project.pbxproj, ParseStarterProject/iOS/ParseStarterProject-Swift/ParseStarterProject/AppDelegate.swift, ParseStarterProject/iOS/ParseStarterProject/ParseStarterProject/ParseStarterProjectAppDelegate.m, ParseStarterProject/watchOS/ParseStarterProject-Swift/ParseStarterProject/AppDelegate.swift
The Starter Projects contained comments that prompted the developer to enable Crash Reporting in their projects. The Parse Crash Reporting tool is has been deprecated in favor of native solutions and will no longer be supported as of March 1, 2016.
=> Remove Crash Reporting references

.gitmodules, Cartfile.private, Cartfile.resolved, Parse.xcodeproj/project.pbxproj, Parse.xcworkspace/contents.xcworkspacedata
This PR moves the submodule reference to the new location under `Carthage/Checkouts/OCMock`, as well as updates OCMock to more up-to-date version.
Please note we are not using dynamic frameworks yet, that is still pending.
Depends on #705.
Contributes to #8
=> Use OCMock checkout via Carthage.

Configurations/ParseUnitTests-OSX.xcconfig, Configurations/ParseUnitTests-iOS.xcconfig, Parse.xcodeproj/project.pbxproj
This PR converts our usage of OCMock from static library to Dynamic Framework.
This also cleans up a lot of header search paths and friends and makes `@import OCMock;` syntax possible!
Depends on #706.
=> Use only dynamic framework version of OCMock.

Configurations/Parse-OSX.xcconfig, Configurations/Parse-iOS.xcconfig, Configurations/Parse-tvOS.xcconfig, Configurations/Parse-watchOS.xcconfig, Configurations/ParseUnitTests-OSX.xcconfig, Configurations/ParseUnitTests-iOS.xcconfig, Parse.xcodeproj/project.pbxproj, Parse.xcworkspace/contents.xcworkspacedata, ParseStarterProject/iOS/ParseStarterProject-Swift/ParseStarterProject-Swift.xcodeproj/project.pbxproj, ParseStarterProject/iOS/ParseStarterProject/ParseStarterProject.xcodeproj/project.pbxproj
This is converting all of our dependencies to use Bolts from dynamic targets.  
Please note, that external build tool targets are still there, as updating the scripts for deployment/starter projects is required to make it work (coming in a separate PR).
Also - this removes all custom set framework search paths as they are no longer required.
Depends on #708 to prevent merge conflicts.
=> Use dynamic framework version of Bolts.

Parse/Internal/PFCommandCache.m
This PR should fix most of CPU time spent here (did some testing and it's waaaay better now).
- Checking the directory file size before enumerating files inside of it - most operations are going to fall into this category, since Command Cache is limited at 10MB.
- Using url directory enumeration with `NSURL` APIs (these are caching the file attributes) instead of simple old string-based directory enumerator.
Closes #712.
=> Improve performance of adding commands to PFCommandCache.

Parse/Internal/User/AuthenticationProviders/Controller/PFUserAuthenticationController.m, Parse/Internal/User/CurrentUserController/PFCurrentUserController.m, Parse/Internal/User/PFUserPrivate.h, Parse/PFACL.m, Parse/PFObject.m, Parse/PFUser.m, Tests/Unit/ACLTests.m
Also added generic types to few of them.
Please note - `authData` needs `id` for object type, since we are using `NSNull` for it in few places.
=> Convert all private ivars of PFUser to properties.

Parse/Internal/PFInternalUtils.m, Parse/Internal/ParseClientConfiguration_Private.h, Parse/Internal/Parse_Private.h, Parse/Parse.m, Parse/ParseClientConfiguration.h, Parse/ParseClientConfiguration.m, Tests/Unit/CommandUnitTests.m, Tests/Unit/ParseClientConfigurationTests.m, Tests/Unit/ParseSetupUnitTests.m
- New property with tests and documentation
- Using new property (please note we are still using the getter from `PFInternalUtils` for legacy test reasons)
- Also improved assertion types on properties of `ParseClientConfiguration` (in a separate commit, though not worth creating a separate PR)
=> Add ability to get/change server url used by the SDK.

Parse/PFConstants.m
Unified across both backend and client.
=> Add proper device type constant for tvOS/watchOS SDKs.

Parse/Internal/Object/PFObjectPrivate.h, Parse/Internal/PFApplication.m, Parse/Internal/PFDevice.m, Parse/Internal/PFFileManager.m, Parse/Internal/PFLocationManager.h, Parse/Internal/PFReachability.m, Parse/PFConstants.h, Parse/PFObject.h, Parse/PFPush.m, Parse/Parse.h, Parse/Parse.m, Tests/Other/ExtensionDataSharing/PFExtensionDataSharingTestHelper.m, Tests/Other/LocationManager/CLLocationManager+TestAdditions.m
- Replace custom, old, Parse-specific macros.
- Replace vague `TARGET_OS_IPHONE`.
=> Unify all platform conditional macros.

Parse/PFObject.m
Regression caused by change in #689.
Old code:
```objc
if (!dirty && ![changes count]) {
```
Broken code:
```objc
if (!dirty && change.count != 0) {
```
Fixed code:
```objc
if (!dirty && change.count == 0) {
```
Boolean logic is my weakness.
=> Fix potentially not saved objects if they are not initially dirty.

Parse/Internal/PFReachability.m, Parse/Internal/ParseManager.h, Parse/Internal/ParseManager.m, Parse/Parse.m
This is no longer needed and is somewhat redundant, since we have `server` property on `ParseClientConfiguration`.
=> Remove redundant serverURL property from ParseManager.

Parse/PFRelation.h, Parse/PFRole.h, Parse/PFRole.m
This was missing - add it and use it.
=> Add generics support to PFRelation.

README.md
=> Add Carthage instructions and badge to README.

Parse/Internal/Query/State/PFMutableQueryState.h, Parse/Internal/Query/State/PFMutableQueryState.m, Parse/PFQuery.h, Parse/PFQuery.m
Thought this was a useful method
=> add includeKeys convenience to PFQuery

Parse/Internal/Commands/CommandRunner/PFCommandRunning.h, Parse/Internal/Commands/CommandRunner/URLRequestConstructor/PFCommandURLRequestConstructor.h, Parse/Internal/Commands/CommandRunner/URLRequestConstructor/PFCommandURLRequestConstructor.m, Parse/Internal/Commands/CommandRunner/URLSession/PFURLSessionCommandRunner.h, Parse/Internal/Commands/CommandRunner/URLSession/PFURLSessionCommandRunner.m, Parse/Internal/ParseModule.h, Parse/Internal/ParseModule.m, Parse/Parse.m, Parse/ParseClientConfiguration.m, Tests/Unit/ParseModuleUnitTests.m, Tests/Unit/ParseSetupUnitTests.m
Implements and closes #826.
cc @hramos
=> Allow clientKey to be nil, as it's not explicitly required for Open Parse Server.

.travis.yml
Re-enable issue with more details -> #850
=> Disable Carthage builds, since it consistently times out on xcodebuild.

Parse/Parse.m, Tests/Unit/ParseSetupUnitTests.m
The old API, since it's using parse.com should still require clientKey.
=> Require clientKey for old SDK initialization API.

Parse.xcodeproj/project.pbxproj, Parse/Internal/Commands/PFRESTQueryCommand.m, Parse/Internal/LocalDataStore/OfflineQueryLogic/PFOfflineQueryLogic.m, Parse/Internal/Query/Controller/PFOfflineQueryController.m, Parse/Internal/Query/PFQueryConstants.h, Parse/Internal/Query/PFQueryConstants.m, Parse/Internal/Query/PFQueryPrivate.h, Parse/Internal/Query/State/PFMutableQueryState.m, Parse/PFQuery.m
I wasn't sure if it would make sense to use the constants in the unit tests, and I left them alone. I'd be happy to update the PR to use the constants in the unit tests, if so desired.
This change is cosmetic, and as such, I didn't add any unit tests.
I wasn't able to run the unit tests due to this build error:
I suspect the error is due to my inexperience with Carthage.
=> Move PFQueryKey constants to their own file to allow reuse throughout the Parse SDK.

Parse/Parse.h
It can be `nil` if Parse is not yet initialized with a configuration.
Fixes #857.
=> Make Parse.+currentConfiguration nullable.

Parse/PFObject.h
=> Fix Swift 2.2 naming conversion for PFObject.+objectWithoutDataWithClassName:objectId:.

Parse/Parse.h, Parse/Parse.m, Tests/Unit/InstallationIdentifierUnitTests.m, Tests/Unit/InstallationUnitTests.m, Tests/Unit/SessionUnitTests.m
We might want to introduce a method that teardowns Parse completely at a later point as well.
What do you think would be a good name for that method? `resetConfiguration`? `deinitialize`?
Also, needed to cleanup these tests, since the setup/teardown logic was inconsistent.
=> Add assertion that makes it invalid to initialize Parse twice in a single runtime.

ParseStarterProject/iOS/ParseStarterProject-Swift/ParseStarterProject/AppDelegate.swift
Line 59, the variable noPushPayload is wrong. The variable is true when there is in fact push pay load. You should compare to nil like this:
noPushPayload = options[UIApplicationLaunchOptionsRemoteNotificationKey] == nil;
If options[UIApplicationLaunchOptionsRemoteNotificationKey]  is nil, then there is no payload...
Thanks,
=> swift AppDelegate - noPushPayload variable is wrong

Parse/Internal/File/Controller/PFFileController.h, Parse/Internal/File/Controller/PFFileController.m, Parse/PFFile.h, Parse/PFFile.m, Tests/Unit/FileControllerTests.m, Tests/Unit/FileUnitTests.m
Adds 2 new methods for clearing cache for a single file or all of them at once.
Fixes #488
=> Add ability to clear PFFile cache.

Parse/Internal/FieldOperation/PFFieldOperation.m, Parse/Internal/Installation/Controller/PFInstallationController.m, Parse/Internal/LocalDataStore/OfflineQueryLogic/PFOfflineQueryLogic.m, Parse/Internal/LocalDataStore/OfflineStore/PFOfflineStore.m, Parse/Internal/PFAssert.h, Parse/Internal/PFEncoder.m, Parse/Internal/PFEventuallyQueue.m, Parse/Internal/PFInternalUtils.m, Parse/Internal/PFPinningEventuallyQueue.m, Parse/Internal/PropertyInfo/PFPropertyInfo_Runtime.m, Parse/Internal/Query/Controller/PFCachedQueryController.m, Parse/Internal/Query/Utilities/PFQueryUtilities.m, Parse/PFObject.m, Parse/PFQuery.m
No more random NSException construction.
Replaced with - `PFParameterAssert`/`PFParameterAssertionFailure` or `PFConsistencyAssert`/`PFConsistencyAssertionFailure`.
Closes #6.
=> Unify and provide consistent client-side error and exception reporting.

Parse/Internal/Installation/CurrentInstallationController/PFCurrentInstallationController.m, Parse/PFInstallation.h, ParseStarterProject/OSX/ParseOSXStarterProject-Swift/ParseOSXStarterProject/AppDelegate.swift, ParseStarterProject/iOS/ParseStarterProject-Swift/ParseStarterProject/AppDelegate.swift, ParseStarterProject/watchOS/ParseStarterProject-Swift/ParseStarterProject/AppDelegate.swift
If reading installationId from disk failed - it will crash the app on setting the installationId.
If loading of `currentInstallation` failed, because disk failed or `installationId` wasn't loaded - we should not crash Swift runtime, but rather force everyone unwrap `currentInstallation`.
Closes #817.
=> Add failure/safety checks for PFInstallation.+currentInstallation.

Parse/Internal/Query/State/PFMutableQueryState.h, Parse/Internal/Query/State/PFMutableQueryState.m, Parse/Internal/Query/State/PFQueryState.h, Parse/Internal/Query/State/PFQueryState.m, Parse/Internal/Query/State/PFQueryState_Private.h, Tests/Unit/QueryStateUnitTests.m
=> Convert constant strings to type-safe macros in PFQueryState.

Parse/PFObject.m
Date type properties are not being converted.
more details here:
https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/issues/945
=> objectWithClassName:dictionary: wasn’t encoding the dictionary into PFOject properly

Parse/Internal/BFTask+Private.m, Parse/Internal/LocalDataStore/OfflineStore/PFOfflineStore.m, Parse/Internal/LocalDataStore/SQLite/PFSQLiteDatabaseController.m, Parse/Internal/PFAsyncTaskQueue.m, Parse/Internal/PFEventuallyQueue.m, Parse/Internal/PFPinningEventuallyQueue.m, Parse/Internal/Query/Controller/PFCachedQueryController.m, Parse/PFObject.m, Parse/PFUser.m, Tests/Unit/ConfigControllerTests.m, Tests/Unit/QueryCachedControllerTests.m, codecov.yml
This is deprecated as of Bolts 1.8.0, so remove all usages of it.
=> Remove all usages of BFTask.exception APIs.

ParseStarterProject/OSX/ParseOSXStarterProject-Swift/ParseOSXStarterProject/AppDelegate.swift, ParseStarterProject/OSX/ParseOSXStarterProject/ParseOSXStarterProject/AppDelegate.m, ParseStarterProject/iOS/ParseStarterProject-Swift/ParseStarterProject/AppDelegate.swift, ParseStarterProject/iOS/ParseStarterProject/ParseStarterProject/ParseStarterProjectAppDelegate.m, ParseStarterProject/tvOS/ParseStarterProject-Swift/ParseStarter/AppDelegate.swift, ParseStarterProject/watchOS/ParseStarterProject-Swift/ParseStarter Extension/ExtensionDelegate.swift, ParseStarterProject/watchOS/ParseStarterProject-Swift/ParseStarterProject/AppDelegate.swift
Superseds #943.
Closes #943.
Fixes #929.
=> Update starter projects to use configuration-based initialization API.

Parse/Internal/Installation/InstallationIdentifierStore/PFInstallationIdentifierStore.m, Tests/Unit/InstallationIdentifierUnitTests.m
Fully propagate the failure to API consumers.
Also added test that verifies the behavior.
Fixes #817. Thank you @fluidsonic for awesome catches and pointers!
=> Fix non-faulted task when loading installationId from persistence group fails.

Parse/Internal/Object/Subclassing/PFObjectSubclassingController.h, Parse/Internal/Object/Subclassing/PFObjectSubclassingController.m, Parse/Internal/PFCoreDataProvider.h, Parse/Internal/PFCoreManager.h, Parse/Internal/PFCoreManager.m, Parse/PFObject+Subclass.h, Parse/PFObject.m, Parse/Parse.m, Tests/Other/TestCases/UnitTestCase/PFUnitTestCase.m, Tests/Unit/ACLTests.m, Tests/Unit/ObjectSubclassPropertiesTests.m, Tests/Unit/ObjectSubclassTests.m, Tests/Unit/ObjectSubclassingControllerTests.m, Tests/Unit/OfflineQueryLogicUnitTests.m, Tests/Unit/PinUnitTests.m, Tests/Unit/SessionControllerTests.m, Tests/Unit/SessionUnitTests.m, Tests/Unit/UserUnitTests.m
Older discussion visible here: #5
Currently, every `PFObject` subclass must be registered with parse before it is used. This can create some hard-to-track-down issues if you're not aware of this, and it isn't exactly the cleanest API.
In Objective-C/Swift, it is relatively easy to search at run-time for subclasses of `PFObject`, and have them register with parse automatically (in the case of dynamic libraries, even as soon as they load from their bundles).
This should prevent needing your app delegate to have lots of extra lines of code related to simply registering all of your `PFObject` subclasses.
- If you had a subclass of `PFObject`, which implemented `PFSubclassing`, but intentionally did not register it with parse (or only conditionally registered it with parse), then you may run …
=> Added automatic PFObject subclass registration.

Parse/Internal/Object/Subclassing/PFObjectSubclassingController.m
Use `NSObject -conformsToProtocol:`, which recursively checks whether a class conforms to protocol or not.
Fixes #975
=> Fix not automatically registered subclasses of built-in subclasses of PFObject.

Parse/Internal/Object/Subclassing/PFObjectSubclassingController.m
Fixes #1006
Makes sure we don't check classes in not loaded bundles.
=> Safely inspect bundles for classes

Parse/Internal/Object/Subclassing/PFObjectSubclassingController.m
Additional safety check related to https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/pull/1090
=> Bundle check

README.md
1. I removed the parse.com link because it redirects to https://parseplatform.github.io which is currently a 404 page.
2. I changed the docs link to the parseplatform.org domain.
3. I changed the blog link from https to http because https doesn't load.
=> Removed or replaced the broken links in the README

Parse/Internal/Object/Subclassing/PFObjectSubclassingController.m
This will help track down the issue should this assert arrise. See @levigroker’s comments in https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/pull/967
=> Outputing offending bundle in assert message.

Parse/Internal/Object/State/PFObjectState.m, Tests/Unit/DecoderTests.m, Tests/Unit/ObjectStateTests.m
Related to: https://github.com/ParsePlatform/parse-server/pull/1946
Original Issue: https://github.com/ParsePlatform/parse-server/issues/1840
In a nutshell:
When performing an unset in Cloud Code the client SDKs need to perform a fetch in order the synchronize their state which is redundant and can possibly break the SoC. 
On parse.com, the bug is present, and the deleted key is not part of the response. No way to know what really happened on cloud code. 
In parse-server, the server responds with a Delete op on the key. 
When serializing the JSON response, `undefined` keys are stripped out of the generated string.
We could have replaced with `null` but that would also require updates on both SDK's to properly handle nulls. and we don't really love `NSNull` on iOS do we?
=> Let the iOS SDK handle Delete ops when sent from the server

Parse/PFObject.m
Problem:
Using instance variable outside of object methods leads to crashes when using composition patterns like decorator or proxy with PFObject.
It violate liskov substitution principle and encapsulation of object.
Is there any reason for this?
=> Use getter instead accessing instance variable

Parse.xcodeproj/project.pbxproj, Parse/PFConstants.h, Parse/Resources/Parse-OSX.Info.plist, Parse/Resources/Parse-iOS.Info.plist, Parse/Resources/Parse-tvOS.Info.plist, Parse/Resources/Parse-watchOS.Info.plist
The PFEncoder.h header was missing from the public folder for the iOS Dynamic Scheme. This fixes it as well as bumps to 1.15.0 to maintain backwards compatibility with LiveQuery Client
=> ⚡️ Release 1.15.0

Parse/Internal/Object/PFObjectPrivate.h, Parse/PFSubclassing.h, Tests/Unit/ProductTests.m, Tests/Unit/PurchaseUnitTests.m, Tests/Unit/UserUnitTests.m
The fix essentailly renames the original ``PFSubclassing.object()`` class method to ``PFSubclassing.instantiateObject()`` method with the same semantics to avoid being flagged by XCode 9 beta 4.
=> Fix #1162 - PFSubclassing.object() class method unavailable since XCode 9 beta 4

Parse/Internal/PFEventuallyQueue.h, Parse/Internal/PFEventuallyQueue.m, Parse/Internal/PFReachability.m, Parse/Internal/ParseManager.m
- a block was capturing self in dealloc through _stopMonitoring
- this removed the retain cycle at dealloc
Fixes #1168
This wasn't crashing before as `dealloc` was never called (cycle). Now that dealloc is properly called, setting `self.connected = YES` was creating a heap corruption as the blocks were not able to correctly retain `self` for executing the `setConnected:` logic
=> Fixes issue related to heap corruption

Parse/Internal/LocalDataStore/OfflineQueryLogic/PFOfflineQueryLogic.m, Parse/Internal/PropertyInfo/PFPropertyInfo.m, Parse/PFObject.m
These are all crashes in the client, all require a non-nil value.
=> Fix some issues where nil was passed to a method requiring a non-nil parameter

Parse/Internal/PFEventuallyQueue.h, Parse/Internal/PFEventuallyQueue.m, Parse/Internal/PFEventuallyQueue_Private.h, Parse/PFObject.m
…and (2) it wasn't actually used in any tests.
=> Remove PFEventuallyQueueTestHelper because (1) it was causing memory leaks in production code

Parse.podspec, Parse/Parse.xcodeproj/project.pbxproj
Move internal headers to `private` section.
=> Expose internal headers

Parse/Parse/PFACL.m
=> Ensure the user has an objectId before resolving ACLs

Parse/Parse/PFObject.m, Parse/Tests/Unit/ObjectUnitTests.m
REST encoding is checking the wrong object, causing a crash on error.
=> Fix wrong precondition bail on REST encoding

ParseStarterProject/OSX/ParseOSXStarterProject-Swift/ParseOSXStarterProject/AppDelegate.swift
It's just a fix to make push notifications work on OSX.
=> Fix on OSX swift example to work push notifications on version 1.17.1

Parse/Parse.xcodeproj/project.pbxproj, Parse/Parse/Internal/Commands/CommandRunner/URLSession/PFURLSessionCommandRunner.m, Parse/Parse/Internal/File/FileDataStream/PFFileDataStream.h, Parse/Parse/Internal/File/PFFileObject_Private.h, Parse/Parse/Internal/PFInternalUtils.m, Parse/Parse/Internal/PFLogging.h, Parse/Parse/Internal/PFSystemLogger.h, Parse/Parse/Internal/PFSystemLogger.m, Parse/Parse/Internal/Purchase/Controller/PFPurchaseController.m, Parse/Parse/PFDecoder.m, Parse/Parse/PFEncoder.m, Parse/Parse/PFFileObject+Deprecated.h, Parse/Parse/PFFileObject+Synchronous.h, Parse/Parse/PFFileObject.h, Parse/Parse/PFFileObject.m, Parse/Parse/PFFileUploadController.h, Parse/Parse/PFObject.m, Parse/Parse/PFProduct.h, Parse/Parse/Parse.h, Parse/Parse/Parse.m, Parse/Tests/Unit/DecoderTests.m, Parse/Tests/Unit/FileUnitTests.m, Parse/Tests/Unit/PurchaseControllerTests.m, ParseUI/Classes/Views/PFImageView.h, ParseUI/Classes/Views/PFImageView.m, ParseUI/ParseUIDemo/Classes/AppDelegate.m, ParseUI/ParseUIDemo/Swift/AppDelegate.swift, ParseUI/ParseUIDemo/Swift/CustomViewControllers/QueryCollectionViewController/SubtitleImageCollectionViewController.swift, ParseUI/ParseUIDemo/Swift/CustomViewControllers/QueryTableViewController/SubtitleImageTableViewController.swift
I needed the fix for #1325 so I took the liberty to use @RyanBertrand's branch and submit it in this PR.
All I did is fix the path of a renamed file in the xcodeproj, change some comments and rewrite the commits history.
I'm not familiar with the development procedure of the Parse SDK, but it builds on my machine, tests are green and the SDK works in my app.
=> Rename PFFile and PFLogger

Parse.podspec, Parse/Parse/Internal/File/PFFileObject_Private.h, Parse/Parse/PFDecoder.m, Parse/Parse/PFFileObject.h, Parse/Parse/PFFileObject.m, Parse/Tests/Unit/FileUnitTests.m, Parse/Tests/Unit/PurchaseControllerTests.m, ParseUI/Generated/PFResources.h, ParseUI/ParseUIDemo/Classes/AppDelegate.m
- Fixed "Argument passed to call that takes no arguments" when declaring PFFileObject(data:contentType) (or so)
- Updated pod to 1.17.2
=> Updated to 1.17.2

README.md
Show popular iOS apps using the Parse iOS SDK.
Just an idea but this may encourage other developers to use Parse in their apps, maybe something similar could be done on the Parse Server repo? - like a markdown file which devs can add their projects too.
=> Add link to Appsight.io

Parse/Parse/PFObject.m
Seen in the wild: many repeated crashes, by just a few users, where `_mergeAfterSaveWithResult` crashes due to `operationSetQueue` being empty and assuming that it has at least one item to pop.
No idea what triggers it.
Band-aid: pre-check and, if the queue is empty at this point, add a dummy empty `PFOperationSet`.
Results: that particular crash no longer appears in our Crashlytics reports. Whether the people in question are now having other difficulties, we don't know. This is obviously a state that shouldn't be reached in the first place, so the band-aid is covering a deeper problem.
ref issue #1262
=> Bandaid for empty operationSetQueue during _mergeAfterSaveWithResult:

Parse/Parse/PFFileObject.h
I updated from 1.17.1 to 1.17.2 and started getting the error `Unknown type name 'PFFile'`.
This PR should point users who eventually update to use the new `PFFileObject` class.
=> Add PFFile to PFFileObject rename warning

Cartfile
Update facebook dependency name to the current one `facebook/facebook-objc-sdk` to avoid having duplicated lines in Cartfile.resolved when importing `facebook/facebook-objc-sdk`.
Without this change I end up having this in my Carthage resolved file:
```
...
github "facebook/facebook-ios-sdk" "v4.42.0"
github "facebook/facebook-objc-sdk" "v4.42.0"
...
```
=> Update facebook dependency name to match current repo name

Parse/Parse/Parse.h, Parse/Parse/Parse.m, Parse/Tests/Other/StoreKitMocking/PFTestSKProductsRequest.m, Parse/Tests/Unit/CommandUnitTests.m, Parse/Tests/Unit/ExtensionDataSharingTests.m
This changes the declaration of class properties in the headers from `+ (Type)property` and `+ (void)setProperty:(Type)value;` to the more modern `@property (class) Type property` where appropriate. 
This has the main advantage of allowing the Swift compiler to differentiate between a property and a method, removing errors like `foo.bar` instead of `foo.bar()` in Swift. 
This should not affect ObjC behaviour in any way. 
In the wake of this I renamed some class methods from `getFoo` to `foo` to keep in line with property naming. The old names are now marked as deprecated.
=> Class properties

Parse.podspec
This should fix the failing nightly Cocoapods build
=> Bumps macOS deployment target to match Bolts

Parse/Parse/Parse.h, Parse/Parse/Parse.m
Added the possibility to set and get the current server URL without having to destroy and re-initialize the client. Example use case: domain failover handling.
Analogous to https://github.com/parse-community/Parse-SDK-Android/pull/985
=> Add get and set server

Parse/Parse/Internal/Commands/CommandRunner/URLSession/PFURLSessionCommandRunner.m
This simple pull request makes it possible to compile Parse-SDK-iOS-OSX for Catalyst. It also requires the following patch to Bolts-ObjC https://github.com/parse-community/Bolts-ObjC/pull/1.
=> Add support for using URLCache on macCatalyst

Parse/Configurations/Parse-macOS.xcconfig, Parse/Parse/Internal/Commands/CommandRunner/URLSession/PFURLSessionCommandRunner.m, Parse/Parse/PFInstallation.m, Parse/Tests/Unit/PinningObjectStoreTests.m
The deprecated API allows the parse SDK to be linked for Mac Catalyst apps and the Xcode 11 SDKs (iOS 13, macOS 10.15, etc.) in general.
In addition to this it also removes the `maccatalyst.` prefix added by Catalyst from the bundle ID. The reasoning is that a Catalyst app should be treated as a iOS App just running on the Mac in all regards. If this is not done some things will not work (e.g. sending push notifications fails since the `topic` is wrong (using `maccatalyst.com.example.app` instead of `com.example.app` which is correct. If the SDK user wants to distinguish Catalyst installations `channels` are a better choice.
=> Don't use NSURLCache API not available in Catalyst

.travis.yml
1. use my github token (i think)
2. only release on tags
see: #1482
=> Try to fix travis (take 1)

.circleci/config.yml
- Updated xctoolchain checkout in gitmodules
- Removed unnecessary code that creates duplicate tvOS simulators
=> Fixing nightly build. 

Parse/Parse/Resources/Parse-iOS.Info.plist
This is an experimental fix for #1491 and #1495.
Just want to see if the tests run ok...
=> Remove iPhoneSimulator

Cartfile, Cartfile.resolved, Parse.podspec
=> FBSDK change from 5.x to 6.x

Parse/Parse.xcodeproj/project.pbxproj, Parse/Parse/Internal/ParseModule.h, Parse/Parse/Internal/ParseModule.m, Parse/Parse/Parse.h, Parse/Parse/Parse.m, Parse/Tests/Other/TestCases/TestCase/PFTestCase.m, Parse/Tests/Other/TestCases/UnitTestCase/PFUnitTestCase.m, Parse/Tests/Unit/FileControllerTests.m, Parse/Tests/Unit/ParseModuleUnitTests.m, Parse/Tests/Unit/PinningObjectStoreTests.m, ParseTwitterUtils/Tests/Unit/OAuth1FlowDialogTests.m
I decided to give those janky tests another shot rather than disable them today. I've made some progress.
These first changes should fix the testFetchPin test. There's some asynchronous action in the synchronous initializeWithConfiguration: method that wasn't handled properly. These changes wrap the asynchronous calls in the method and send a notification when all the work is actually done. This allows us to wait for the notification in our tests before proceeding, fixing the crash in the test.
I preferred this to changing the method signature of our init method to avoid breaking existing installs.
=> Fixing intermittent test failures

Parse/Tests/Other/OCMock/OCMock+Parse.m
Small catch I found while looking through code to port to Parse-Swift. Not sure if it effects anything, but if I see things that are quick fixes, I'll submit them.
=> Fix capitalization in OCKMock

Parse/Parse/ParseClientConfiguration.m
This fixes #1526 .
I checked that `ParseClientConfigurationTests` (Scheme "Parse-masOS") passes for Xcode 11.6 and Xcode 12 beta 4.
=> Fix "Incompatible block pointer types" error

Parse/Parse/Internal/PFGeoPointPrivate.h, Parse/Parse/Internal/PFLogging.h, Parse/Parse/Internal/PFSystemLogger.h, Parse/Parse/Internal/ParseModule.h
First of all - thanks to the maintainers for your work on this project! It was a relief (and still is) to not have to migrate off of Parse. 
**Contribution guidelines**
[x] 1. Fork the repo and create your branch from master.
[x] 2. Add unit tests for any new code you add. → No new code added, so I did not add any tests. 
[x] 3. If you've changed APIs, update the documentation and the iOS Guide
[x] 4. Ensure the test suite passes. → Tests around extensions failed both with and without my changes; these do not seem to be related to this change.
[x] 5. Make sure your code follows the style guide
This PR is a simple fix for issue #1545 based on the discussion that was there. 
When I compiled the code locally it indicated an import error for `@import Bolts` however Xcode still let everything …
=> Fixes xcode12 bolts compile error

.travis.yml, Parse/Parse.xcodeproj/project.pbxproj
This makes it possible to build Parse SDK for maccatalyst by "checking the box".
=> Allow Parse SDK to be built for maccatalyst

.circleci/config.yml, .travis.yml, CHANGELOG.md, Parse.podspec, Parse/Parse.xcodeproj/project.pbxproj, Parse/Parse/PFConstants.h, Parse/Parse/Resources/Parse-OSX.Info.plist, Parse/Parse/Resources/Parse-iOS.Info.plist, Parse/Parse/Resources/Parse-tvOS.Info.plist, Parse/Parse/Resources/Parse-watchOS.Info.plist, ParseFacebookUtils/Resources/Info-iOS.plist, ParseFacebookUtils/Resources/Info-tvOS.plist, ParseStarterProject/OSX/ParseOSXStarterProject-Swift/Resources/Info.plist, ParseStarterProject/OSX/ParseOSXStarterProject/Resources/Info.plist, ParseStarterProject/iOS/ParseStarterProject-Swift/Resources/Info.plist, ParseStarterProject/iOS/ParseStarterProject/Resources/Info.plist, ParseStarterProject/tvOS/ParseStarterProject-Swift/ParseStarter/Info.plist, ParseStarterProject/watchOS/ParseStarterProject-Swift/ParseStarter Extension/Info.plist, ParseStarterProject/watchOS/ParseStarterProject-Swift/ParseStarter/Info.plist, ParseStarterProject/watchOS/ParseStarterProject-Swift/Resources/Info.plist, ParseTwitterUtils/Resources/Info.plist, ParseUI/Classes/LogInViewController/PFLogInViewController.h, ParseUI/Classes/LogInViewController/PFLogInViewController.m, ParseUI/ParseUI.xcodeproj/project.pbxproj, ParseUI/Resources/Info.plist, ParseUI/Sign In With Apple/PFAppleUtils.h, ParseUI/Sign In With Apple/PFAppleUtils.m, ParseUI/SignInWithAppleTests/SignInWithAppleTests.m
=> Release 1.19.1

Cartfile.resolved, Parse.podspec, ParseFacebookUtils/Tests/Unit/FacebookAuthenticationProviderTests.m
Updated FBSDK to v9.0
According to the docs, Facebook introduced a new login method with v9.0 with "limited data mode", which is not covered by this PR. The old login method is still present on v9.0 and working just fine with Parse.
Given that [Facebook is deprecating all previous SDKs](https://developers.facebook.com/blog/post/2021/01/19/introducing-facebook-platform-sdk-version-9/), I think it would be a good idea to integrate v9.0 now, and leave the new login mode for later (though I haven't check what/if changes are needed).
=> Updated FBSDK to 9.0

README.md
CircleCI pipeline link was broken in the shield icon - this points to the right pipeline
=> docs: fix CircleCI build status link in README

.github/workflows/release-manual-cocoapods.yml
Adds a manual cocoapods release workflow.
Related issue: #n/a
Adds manual cocoapods release workflow.
n/a
=> ci: add manual cocoapods release workflow

.github/workflows/release-automated.yml
The release requires carthage to be installed.
Closes: #n/a
Switching to macos-11 image which has carthage preinstalled.
n/a
=> ci: Assets not building with auto-release workflow

.github/workflows/release-automated.yml
Auto-release workflow fails because semantic-release requires Node >= 18
Closes: #n/a
Upgrade to Node 18
n/a
=> ci: Fix semantic release requires Node >=18

.github/workflows/release-manual-docs.yml
If docs creation fails, there is no way to manually trigger it again.
Closes: #n/a
Add workflow to manually trigger docs creation.
=> ci: Add manual docs publish workflow

Parse/Parse/Internal/PFInternalUtils.h, Parse/Parse/Internal/PFInternalUtils.m, Parse/Parse/Source/Parse.h, Parse/Parse/Source/Parse.m
Closes: https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1528
- Remove unused `PFInternalUtils.setParseServer`
- Completely re-init SDK when setting new server URL
=> fix: `Parse.setServer` does not set new server URL

Parse/Parse/Internal/User/AuthenticationProviders/Controller/PFUserAuthenticationController.m, Parse/Parse/Source/PFUser.h, Parse/Parse/Source/PFUser.m
SDK asserts that auth delegate can only be registered once.
Closes: #n/a
Gracefully deregister existing auth delegate and register new delegate instead of crashing.
n/a
=> feat: Add `PFUser.unregisterAuthenticationDelegate` and allow to register delegate gracefully if another delegate is already registered

Parse/Parse/Internal/User/AuthenticationProviders/Controller/PFUserAuthenticationController.m
When registering the same auth delegate again, it is actually fully re-registered in the SDK.
Closes: #n/a
Don't register same auth delegate again if its already registered. Instead just do nothing.
=> perf: Skip registering auth delegate if it's already registered

Scripts/jazzy.sh
Parse.h header file was moved in https://github.com/parse-community/Parse-SDK-iOS-OSX/pull/1683 preventing the api documentation from generating. 
```
error: error reading '/Users/runner/work/Parse-SDK-iOS-OSX/Parse-SDK-iOS-OSX/Parse/Parse/Parse.h'
```
Closes: https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1702
* Allow jazzy script to fail with non-zero exit code
* Correct the proper header path
=> ci: API reference documentation not generated

.github/workflows/ci.yml, .github/workflows/release-manual-docs.yml
Dependencies used to generate docs are missing.
Closes: https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1702
* Install carthage submodules
* Remove the dependency on `parseui` test suite to generate docs.
=> ci: Fix manual documentation publishing workflow

.github/workflows/ci.yml
Adds concurrency to minimise the amount of outdated workflows that are run.
Closes: n/a
n/a
=> ci: Add concurrency to cancel previous workflow runs

Parse/Parse/Internal/Commands/PFRESTQueryCommand.h, Parse/Parse/Internal/Commands/PFRESTQueryCommand.m, Parse/Parse/Internal/Query/State/PFMutableQueryState.h, Parse/Parse/Internal/Query/State/PFMutableQueryState.m, Parse/Parse/Internal/Query/State/PFQueryState.h, Parse/Parse/Internal/Query/State/PFQueryState.m, Parse/Parse/Internal/Query/State/PFQueryState_Private.h, Parse/Parse/Source/PFQuery.h, Parse/Parse/Source/PFQuery.m, Parse/Tests/Other/TestCases/UnitTestCase/PFUnitTestCase.m, Parse/Tests/Unit/QueryStateUnitTests.m, Parse/Tests/Unit/QueryUnitTests.m
Added support for parameter excludeKeys in queries (similar to select keys) in order to exclude the desired fields from retrieved objects.
Added in Parse-Server 3.6.0 https://github.com/parse-community/parse-server/pull/5737
=> feat: Add support to exclude `PFObject` fields in query results with `PFQuery.excludeKeys`

Parse/Parse/Internal/LocalDataStore/OfflineQueryLogic/PFOfflineQueryLogic.m, Parse/Parse/Internal/Query/PFQueryConstants.h, Parse/Parse/Internal/Query/PFQueryConstants.m, Parse/Parse/Source/PFQuery.h, Parse/Parse/Source/PFQuery.m, Parse/Tests/Unit/OfflineQueryLogicUnitTests.m, Parse/Tests/Unit/QueryUnitTests.m
Adds PFQuery and LiveQuery support for `$containedBy` query
Ref: https://github.com/parse-community/parse-server/pull/4766
Closes: n/a
=> feat: Add support for `PFQuery.containedBy`

Parse/Parse/Internal/Purchase/Controller/PFPurchaseController.m
PFProduct and PFPurchase aren't supported on MacOS
Closes: https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1699
* Remove PFPurchaseController from Mac build
=> fix: Compilation error on macOS `Undefined symbol: OBJC_CLASS$_PFProductsRequestHandler`

.github/workflows/ci.yml, CONTRIBUTING.md, Parse.xcworkspace/xcshareddata/swiftpm/Package.resolved, ParseStarterProject/OSX/ParseOSXStarterProject-Swift/ParseOSXStarterProject-Swift.xcodeproj/project.pbxproj, ParseStarterProject/OSX/ParseOSXStarterProject-Swift/ParseOSXStarterProject-Swift.xcodeproj/project.xcworkspace/contents.xcworkspacedata, ParseStarterProject/OSX/ParseOSXStarterProject-Swift/ParseOSXStarterProject-Swift.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, ParseStarterProject/OSX/ParseOSXStarterProject-Swift/ParseOSXStarterProject/AppDelegate.swift, ParseStarterProject/OSX/ParseOSXStarterProject/ParseOSXStarterProject.xcodeproj/project.pbxproj, ParseStarterProject/OSX/ParseOSXStarterProject/ParseOSXStarterProject.xcodeproj/project.xcworkspace/contents.xcworkspacedata, ParseStarterProject/OSX/ParseOSXStarterProject/ParseOSXStarterProject.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, ParseStarterProject/OSX/ParseOSXStarterProject/ParseOSXStarterProject/AppDelegate.m, ParseStarterProject/iOS/ParseStarterProject-Swift/ParseStarterProject-Swift.xcodeproj/project.pbxproj, ParseStarterProject/iOS/ParseStarterProject-Swift/ParseStarterProject-Swift.xcodeproj/project.xcworkspace/contents.xcworkspacedata, ParseStarterProject/iOS/ParseStarterProject-Swift/ParseStarterProject-Swift.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, ParseStarterProject/iOS/ParseStarterProject-Swift/ParseStarterProject/AppDelegate.swift, ParseStarterProject/iOS/ParseStarterProject-Swift/ParseStarterProject/ViewController.swift, ParseStarterProject/iOS/ParseStarterProject/ParseStarterProject.xcodeproj/project.pbxproj, ParseStarterProject/iOS/ParseStarterProject/ParseStarterProject.xcodeproj/project.xcworkspace/contents.xcworkspacedata, ParseStarterProject/iOS/ParseStarterProject/ParseStarterProject.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, ParseStarterProject/iOS/ParseStarterProject/ParseStarterProject/ParseStarterProjectAppDelegate.m, ParseStarterProject/iOS/ParseStarterProject/ParseStarterProject/ParseStarterProjectViewController.m, ParseStarterProject/watchOS/ParseStarterProject-Swift/ParseStarter Extension/ExtensionDelegate.swift, ParseStarterProject/watchOS/ParseStarterProject-Swift/ParseStarter Extension/InterfaceController.swift, ParseStarterProject/watchOS/ParseStarterProject-Swift/ParseStarter-Swift.xcodeproj/project.pbxproj, ParseStarterProject/watchOS/ParseStarterProject-Swift/ParseStarter-Swift.xcodeproj/project.xcworkspace/contents.xcworkspacedata, ParseStarterProject/watchOS/ParseStarterProject-Swift/ParseStarter-Swift.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Rakefile
The code for building starter projects does exists but was never used and didn't work when used.
Because they weren't use a lot of issues could have been caught.
* Use SPM for all projects
* Update Rakefile with new commands
* Add build to CI
* Remove package release build
=> ci: Fix and build Starter Projects

README.md, Rakefile
xctoolchain framework builder doesn't work for release configuration builds on Xcode 14+. 
Closes: N/A
Eventually we would want to create xcframework assets for publishing. We can use [swift-create-xcframework](https://github.com/unsignedapps/swift-create-xcframework) or this [Makefile](https://github.com/dplewis/Parse-SDK-iOS-OSX/blob/xcframework/Makefile) that I'm testing. They far are simpler solutions than working with xctoolchain.
=> refactor: Remove framework builder for assets

.github/workflows/ci.yml, .github/workflows/release-automated.yml, .github/workflows/release-manual-docs.yml, CONTRIBUTING.md
Closes: #1777 
Pin bundler version to not use latest version that requires ruby >= 3
=> ci: Fix failing CI by pinning bundler version

Gemfile, Gemfile.lock, Rakefile
=> ci: Fix release workflow

Parse/Parse/Internal/Commands/CommandRunner/PFCommandRunningConstants.h, Parse/Parse/Internal/Commands/CommandRunner/PFCommandRunningConstants.m, Parse/Parse/Internal/Commands/CommandRunner/URLRequestConstructor/PFCommandURLRequestConstructor.m, Parse/Parse/Source/PFConstants.h, Parse/Tests/Unit/CommandURLRequestConstructorTests.m
Idempotency is a feature on the server to prevent duplicate requests. A unique requestId must be added per request to ensure it works. 
https://github.com/parse-community/parse-server/pull/6748
Add a requestId to every request. This feature must be enabled on the server to work. Add DUPLICATE_REQUEST error code
=> feat: Add idempotency

.github/workflows/ci.yml
Fixes Ci timeout, see for ex: https://github.com/parse-community/Parse-SDK-iOS-OSX/actions/runs/10906352787/job/30538838978?pr=1808
=> ci: Fix CI timeout

Parse/Parse/Internal/Object/Subclassing/PFObjectSubclassingController.m
App crashes on app startup when built with Xcode 16:
> The class PFPin must be registered with registerSubclass before using Parse
Closes: https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1792
Starting Xcode 16, Apple adds this new build setting in Xcode: ENABLE_DEBUG_DYLIB, enabled by default.
Per Apple's [doc](https://developer.apple.com/documentation/xcode/build-settings-reference#Enable-Debug-Dylib-Support): 
> If enabled, debug builds of app and app extension targets on supported platforms and SDKs will be built with the main binary code in a separate “NAME.debug.dylib”. 
When getting class names from a binary, we should check on the "NAME.debug.dylib" binary file as well, instead of assuming the "NAME" binary file.
=> fix: App crashes on launch and SwiftUI preview when built with Xcode 16 due to unregistered Parse subclasses

.github/workflows/ci.yml, Package.resolved, Package.swift, Parse.xcworkspace/xcshareddata/swiftpm/Package.resolved, Parse/Parse.xcodeproj/project.pbxproj
Fixes issue when running test on Xcode 16.1 RC / beta. Previously 3.9.2
```
xxx/NSObject+OCMAdditions.m:49:14: Incompatible function pointer types returning 'void (id _Nonnull, SEL _Nonnull, ...)' from a function with result type 'IMP' (aka 'id  _Nullable (*)(id _Nonnull, SEL _Nonnull, ...)')
```
https://github.com/erikdoe/ocmock/releases/tag/v3.9.4
=> refactor: Bump OCMock to 3.9.4

README.md
The purpose of this PR is to trigger a release. The changes for Xcode 16 support have been done in https://github.com/parse-community/Parse-SDK-iOS-OSX/pull/1818, which was merged as `ci` instead of `feat` and hence did not trigger a release.
=> feat: Add support for Xcode 16

Parse/Parse/Source/PFObject.h, Parse/Parse/Source/PFObject.m, Parse/Tests/Unit/ObjectUnitTests.m, Rakefile
There is no way easy way to convert a dictionary to a PFObject. This is useful if you return a json server side and want to decode it client side. Analogous to `Parse.Object.fromJSON` in the JS SDK
Add a wrapper around the private method `_objectFromDictionary`
=> feat: Add `PFObject.fromDictionary` to create an object from dictionary

Parse/Parse.xcodeproj/xcshareddata/xcschemes/Parse-iOS.xcscheme, Parse/Parse/Source/ParseClientConfiguration.m
ParseClientConfigurationTests.testServerValidation test is broken and was excluded from the test suite.
Closes: https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1837
Improve url validation, we could also remove this check and leave it to the developer
=> fix: `Parse.setServer` doesn't properly validate URL
